### ISSUE TITLE
Make the timezone configurable

### ISSUE THREAD

**Issue by ThiefMaster** [mattermost/mattermost-plugin-github#109]
My whole team is in Europe/Zurich, but the timestamps in the plugin messages are always UTC.
It'd be nice if the timezone used in these messages could be configured (or if they were adapted to the local timezone of whoever is viewing it).

**Comment by jasonblais** [comment]
I'm actually curious how useful people find the time & date in GitHub notifications, given the Mattermost post itself has a timestamp in the user's own timezone.

**Comment by jasonblais** [comment]
From @mickmister - 

> I think it's useful for glancing at the date portion of the timestamp. The time isn't localized so it is near useless

**Comment by hanzei** [comment]
:+1: for removing the timestamp. Mattermost shows the time of the message anyway.

**Comment by Deverick-Simpson** [comment]
I'll snag this one.

**Comment by hanzei** [comment]
Thanks @Deverick-Simpson. Please note the comment above https://github.com/mattermost/mattermost-plugin-github/issues/109#issuecomment-515416438 on how this issue should be resolved.

**Comment by levb** [comment]
@Deverick-Simpson just checking in, any progress?
