### ISSUE TITLE
Link on RHS are not limited to organisation 

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#113]
When clicking on the of the links on the RHS, a new windows opens up in github. But the PRs/issues shown there are not limited to the organisation.

**Comment by hanzei** [comment]
Update: This bug only occurs after a user just connected his/her account. After a refresh of the page, it links are fine.

**Comment by hanzei** [comment]
I think we can move this to `v0.12`. It's only a problem on after the first connection.

**Comment by larkox** [comment]
May [this PR](https://github.com/mattermost/mattermost-plugin-github/pull/164) have solved this?

**Comment by hanzei** [comment]
Maybe. @DHaussermann Would you please, when testing https://github.com/mattermost/mattermost-plugin-github/pull/164, also test if this ticket got fixed?

**Comment by hanzei** [comment]
Closing as #164 likely resolved this.
