### ISSUE TITLE
RHS behavious badly if there are too many label on a PR

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#114]
When a PR has too manly labels the RHS looks and behaves weird:
- The title is broken into two line
- The last label is cur off
- You can scroll to the right to show the last label
![Screenshot from 2019-08-12 10-19-52](https://user-images.githubusercontent.com/16541325/62852924-2116f580-bceb-11e9-8537-8948d9a07752.png)

**Comment by hanzei** [comment]
cc @marianunez

**Comment by marianunez** [comment]
I've created a JIRA ticket [MM-17864](https://mattermost.atlassian.net/browse/MM-17864) to triage and track this.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-github/pull/117
