### ISSUE TITLE
Add "Create Github Issue" similar to Jira plugin

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-github#118]
Example from the Mattermost Jira plugin:

![image](https://user-images.githubusercontent.com/1187448/64528188-b42c5680-d2bc-11e9-8904-9a85207ff255.png)

See https://github.com/mattermost/mattermost-plugin-jira

https://mattermost.atlassian.net/browse/MM-18132

**Comment by dhadiseputro** [comment]
@levb I am interested in helping this. Is the goal of this to be able to create github issues via `/github create issues <title> <body> ...`?

**Comment by levb** [comment]
@dhadiseputro Thank you for taking a look at this issue! What you proposed would be the simplest implementation. In the Jira plugin we support UI from the `...` menu of a post, it pre-populates the issue description, and has (limited) support for other custom fields. Ultimately we'd want something like that.

**Comment by dhadiseputro** [comment]
I see, can you show me the UI part for the Jira plugin? I am not too great with UI, I can follow what you have in Jira and expand on that. I am thinking that the UI modal to be triggered by `/github create issue`?

**Comment by levb** [comment]
@dhadiseputro We just had another contributor submit a similar change, https://github.com/mattermost/mattermost-plugin-github/pull/120. The Jira plugin is at https://github.com/mattermost/mattermost-plugin-jira; the most relevant UI file is probably https://github.com/mattermost/mattermost-plugin-jira/tree/master/webapp/src/components/modals/create_issue, should be a good entry-point anyway. The server-side implementation for Jira is mostly in https://github.com/mattermost/mattermost-plugin-jira/blob/master/server/issue.go

**Comment by dhadiseputro** [comment]
thanks! I will take a look at #120 and add upon it to create new github issues.

**Comment by dhadiseputro** [comment]
can you show me where the entry point for `/jira create`? I am looking for it in command.go (https://github.com/mattermost/mattermost-plugin-jira/blob/master/server/command.go#L46), it does not have `create`. I am kinda new here, so please bear with me :)
Thanks!

**Comment by niklabh** [comment]
You have to create a create issue handler in server/api.go like this: https://github.com/mattermost/mattermost-plugin-github/pull/120/files#diff-0d5a44e9b96f048fa52b477ce6be6253R532 . We are using google github client. It has a function to create issue. 

    githubClient.Issues.Create(ctx context.Context, owner string, repo string, issue *github.IssueRequest) (*github.Issue, *github.Response, error)

Then you have to add a context menu item in message similar to https://github.com/mattermost/mattermost-plugin-github/pull/120 to create new issue from webapp.

**Comment by niklabh** [comment]
The entry point in jira plugin is not a slash command but drop down menu register in jira plugin.jsx https://github.com/mattermost/mattermost-plugin-jira/blob/402eed5de9974e83b18c14acfe3a579fd5921c9c/webapp/src/plugin.jsx#L31

Hope that helps. If you need more help you can ping me on @niklabh in community.mattermost.com

**Comment by dhadiseputro** [comment]
Okay thanks a lot! That really helps! :)

**Comment by niklabh** [comment]
Its the react class which is being connected with redux at line 28

**Comment by dhadiseputro** [comment]
If I have some questions, can I create a PR to show you guys what I have so far?

**Comment by hanzei** [comment]
Sure, we can always provide feedback on a WIP PR.

**Comment by dhadiseputro** [comment]
okay will clean it up in a bit and create the PR

**Comment by dhadiseputro** [comment]
#123
