### ISSUE TITLE
Add "Attach to Github Issue" similar to Jira plugin

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-github#119]
Example from the Mattermost Jira plugin:

![image](https://user-images.githubusercontent.com/1187448/64528448-65cb8780-d2bd-11e9-8871-3f675fede784.png)

See https://github.com/mattermost/mattermost-plugin-jira

https://mattermost.atlassian.net/browse/MM-18132

**Comment by niklabh** [comment]
Hey, i would love to work on this.

**Comment by mgdelacroix** [comment]
Thanks @niklabh!

**Comment by niklabh** [comment]
Here is a pull request: https://github.com/mattermost/mattermost-plugin-github/pull/120

**Comment by niklabh** [comment]
Here is the flow for implementations in https://github.com/mattermost/mattermost-plugin-github/pull/120:
- Click Attach to Github Issue in context menu (shown when user connects his github account with plugin installed) on non system messages
![Screenshot from 2019-09-11 13-26-14](https://user-images.githubusercontent.com/874046/64694622-55243880-d49a-11e9-819e-bc8f32685f00.png)
- Attach to github modal will open
![Screenshot from 2019-09-11 13-26-30](https://user-images.githubusercontent.com/874046/64694655-6b31f900-d49a-11e9-8428-84bbd386f884.png)
- You can search the issue. The query to github is is:open is:issue assignee:{connected_user} archived:false [org:{organisation}] [search term]
![Screenshot from 2019-09-11 13-26-47](https://user-images.githubusercontent.com/874046/64694708-9ae10100-d49a-11e9-915f-bd1fa4a4cf3b.png)
- Comment is attached to github
![Screenshot from 2019-09-11 13-37-28](https://user-images.githubusercontent.com/874046/64694735-aaf8e080-d49a-11e9-8df7-e9c2d9548169.png)

**Comment by niklabh** [comment]
asdamsdasdasd

**Comment by AnXh3L0** [comment]
@niklabh Hi, we are using this plugin on a Mattermost instance of ours but the result after attaching a Mattermost message to an issue is not the same.

Yours contains just the message and that's it, meanwhile ours also adds some unwanted comments on the top, such as, "x user attached x message to issue".

Is there any config I have missed or did this feature actually change in newer PRs? Thanks in advance!

**Comment by hanzei** [comment]
Hi @AnXh3L0,

The screenshot above were taken from a WIP prototype. https://github.com/mattermost/mattermost-plugin-github/pull/162 did add the `, "x user attached x message to issue` text. It there to make clear where is comment does come from and help with linking Mattermost and GitHub even further together.

**Comment by AnXh3L0** [comment]
Hi @hanzei,

Thanks for the answer. Is there any way we can remove that line without having to edit and rebuild the whole plugin?

**Comment by hanzei** [comment]
No, there isn't. Without that lint it seams to be hard to identify the context in which a message was attached e.g. when attaching a message from another user.

**Comment by AnXh3L0** [comment]
Understood, it seems I'll have to edit the plugin myself then, thanks for the quick answer!
