### ISSUE TITLE
Build a github action to Post to Mattermost

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-github#135]
Similar or better to https://github.com/apex/actions/tree/master/slack

See https://github.com/actions for more info on github actions

**Comment by levb** [comment]
Eventually, we should be here, https://github.com/marketplace?category=chat&type=actions

**Comment by kumar1202** [comment]
Hi, I would like to work on this.

**Comment by levb** [comment]
Apparently, I missed https://github.com/cpanato/action-mattermost-notify - already exists, thanks to @cpanato !
