### ISSUE TITLE
octopus icon randomly changes where it points to

### ISSUE THREAD

**Issue by wwalker** [mattermost/mattermost-plugin-github#139]
GitHub (github - 0.9.2)
GitHub plugin for Mattermost.

We are running on GithubEnterprise.

We have Enterprise Base URL and Enterprise Upload URL set to https://github.ourdomain.com

the octocat in the left bottom, sometimes points to https://github.com/settings/connections/applications/09a864219be324547cea1
and other times points to https://github.ourdomain.com/settings/connections/applications/09a864219be324547cea1

I can't get it to change, it just does what it wants.  Currently, all the icons down there point to github.com and therefore don't work.

**Comment by wwalker** [comment]
![gh](https://user-images.githubusercontent.com/23478/66520749-64090580-eaaf-11e9-82e8-3b7cff77589d.png)

**Comment by wwalker** [comment]
Also, I have tested this in Google Chrome Version 77.0.3865.90 (Official Build) (64-bit) and Mozilla Firefox 69.0.1 both on Fedora 30

**Comment by wwalker** [comment]
And now they are pointing again where they should. (no config change, no restart, nothing done to change the behavior
![ghe](https://user-images.githubusercontent.com/23478/66522685-a0d6fb80-eab3-11e9-8d6b-34af6d10d0b1.png)

**Comment by hanzei** [comment]
This is likely a duplicate of https://github.com/mattermost/mattermost-plugin-github/issues/113 and  https://github.com/mattermost/mattermost-plugin-gitlab/issues/74

**Comment by larkox** [comment]
May I take this one? I just uploaded a solution for gitlab and I am pretty sure the solution here is the same.
