### ISSUE TITLE
The column on the left where the octocat icon shows up, is not visible for MM users that are only in 1 team.

### ISSUE THREAD

**Issue by wwalker** [mattermost/mattermost-plugin-github#140]
the members of my dept. can't see the octocat icon, because they are only in one MM "team" and therefore don't have the strip on the left of the screen where the octocat icon shows up.

If I add them to a second MM "team" then they see the strip and the octocat

I don't know if this is a bug in that github plugin should cause that strip to show up, or if it is a bug in MM client.

**Comment by marianunez** [comment]
Hi @wwalker! When there is only one team you should see the Github plugin action buttons at the top of the left-hand sidebar below the Main Menu as shown below: 

<img width="233" alt="Screen Shot 2019-10-09 at 5 57 24 PM" src="https://user-images.githubusercontent.com/936315/66523771-b867b180-eabe-11e9-95c8-c36afacf9f02.png">

Had the users that could not see the plugin buttons connected their github account yet with `/github connect`? 

Also, what version of Mattermost Server are you running?

**Comment by wwalker** [comment]
even after they've set up github plugin, if they get down to only one team, the strip on the left disappears and they have no access to the github plugin :-(

**Comment by wwalker** [comment]
Doh! @marianunez you are correct.  Closing
