### ISSUE TITLE
Make access to KV store atomically safe when saving/removing subscriptions

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#141]
#### Summary

For subscriptions of GitHub projects to MM channels, all of the subscription configuration is stored in the `subscriptions` portion of the KV store slice that is used by the Github plugin. In order to avoid race conditions and conflicts when two users are concurrently editing subscriptions, we should wrap the operations in a function like `atomicModify` used [in the Jira plugin](https://github.com/mattermost/mattermost-plugin-jira/blob/8d1a96baeb46dd18eca50511a6cc49b4892be1a8/server/subscribe.go#L345).

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18722

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: GitHub" community channel](https://community.mattermost.com/core/channels/github-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by gsagula** [comment]
I'll take this one.

**Comment by gsagula** [comment]
@mickmister @hanzei Quick update: This issue is part of my tryout but I won't be able to start working on it until Oct 28.

cc: @jwilander

**Comment by hanzei** [comment]
Thanks for the heads up @gsagula. Looking forward to you working on this :+1:

**Comment by gsagula** [comment]
@mickmister @hanzei Quick question before I start working on this issue. If I understand it correctly, [`atomicModify`](https://github.com/mattermost/mattermost-plugin-jira/blob/8d1a96baeb46dd18eca50511a6cc49b4892be1a8/server/subscribe.go#L345) function  should attempt to modify the the subscriptions only when the key exists in the KV storage and the initial value is equal to the current value. I'm not sure why `true` is being passed to `success`  [here](https://github.com/mattermost/mattermost-plugin-jira/blob/8d1a96baeb46dd18eca50511a6cc49b4892be1a8/server/subscribe.go#L369):
```
success := false
for !success {
	initialBytes, newValue, err := readModify()
	if err != nil {
		return err
	}

	var setError *model.AppError
	success, setError = p.API.KVCompareAndSet(key, initialBytes, newValue)
	success = true
	if setError != nil {
		return errors.Wrap(setError, "problem writing value")
	}
}
```
Should this loop continue when `p.API.KVCompareAndSet(key, initialBytes, newValue)` returns `false, nil`, so that `readModify` can fetch new initial bytes and `KVCompareAndSet` can attempt to set the modified bytes again?

**Comment by mickmister** [comment]
Hi @gsagula,

It seems that the `success = true` line may be a bug. This line was introduced before the switch to using `api.KVCompareAndSet`, which gives us a success return value, but the `success = true` line was kept as well, ([before](https://github.com/mattermost/mattermost-plugin-jira/pull/61/files#diff-2e60f7eae1ef5d6971c9403310a9bdb5R301) and [after](https://github.com/mattermost/mattermost-plugin-jira/pull/243/files#diff-2e60f7eae1ef5d6971c9403310a9bdb5R366)). It makes sense to me to use the `success` value returned from `KVCompareAndSet` instead of the hardcode below the call. @crspeller do you know if leaving the `success = true` line was intentional after the switch?

Also, there was discussion about making the function into a helper (including a retry limit), so multiple plugins can reuse the same code: https://github.com/mattermost/mattermost-plugin-jira/pull/61/files#r286163455 . This is probably a good route to take for this ticket. What are your thoughts @gsagula?

**Comment by gsagula** [comment]
Thanks @mickmister,

I agree with limiting the retries. Anything that allows controlling bursts so we can minimize chances of resource starvation. Something like a [token bucket](https://en.wikipedia.org/wiki/Token_bucket)  should probably be sufficient. WDYT?

I'm still getting familiar with the design. Is  [helpers_kv.go](https://github.com/mattermost/mattermost-server/blob/master/plugin/helpers_kv.go) a good place to implement the helper?

**Comment by mickmister** [comment]
> Something like a token bucket should probably be enough. WDYT?

Looks like a great solution, looking forward to the implementation!

> I'm still getting familiar with the design. Is helpers_kv.go  a good place to implement the helper?

Yep :+1:

**Comment by levb** [comment]
@gsagula do we still need this ticket, or has it been (indirectly?) resolved?

**Comment by gsagula** [comment]
I need to finish https://github.com/mattermost/mattermost-server/pull/13002 before getting back to this one.

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-server/pull/13805 has to be done first
