### ISSUE TITLE
Make links to comments have the full comment link in the URL

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#142]
#### Summary

Currently, a `(username) commented on your pull request` DM message from the Github bot will link to the associated pull request or issue, but will not include the full link to the comment. Because of this, the user is not taken directly to the comment when they click the link.

To improve UX of this feature, the user should be taken to the comment or review that caused the notification.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-19443

**Comment by malaDev** [comment]
I pick this one

**Comment by mickmister** [comment]
Awesome, thanks @malaDev!
