### ISSUE TITLE
"Attach to GitHub issue" menu item misaligned and spelled incorrectly

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-github#144]
Icons with GitHub and Jira plugins not aligned / different size. Same for text

`GitHub` is spelled as `Github`

![image](https://user-images.githubusercontent.com/13119842/66926359-e6d41800-effb-11e9-8ee9-2cd64c50758c.png)

**Comment by esethna** [comment]
FYI ticket was opened for this earlier: https://mattermost.atlassian.net/browse/MM-19494

0/5 on process, so feel free to open or close as required

**Comment by hanzei** [comment]
Let's keep this open for visibility.

**Comment by levb** [comment]
https://mattermost.atlassian.net/browse/MM-19494 has been fixed.
