### ISSUE TITLE
[MM-19444] Include number of approvals in RHS PR view

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#151]
#### Summary

When displaying "your open pull requests" or similar view in the RHS, the number of approvals so far on the PR would be helpful. It can help determine whether the PR has a stale label.

For example: If a PR has 3 or 4 approvals, chances are it should have the "Reviews Complete" label and not "Dev Review" or "QA Review" labels. It's just another short piece of info available without leaving MM.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-19444

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. You can join the [GitHub plugin channel](https://community.mattermost.com/core/channels/github-plugin) for discussion on this task.

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by M-ZubairAhmed** [comment]
Can i work on this

**Comment by mickmister** [comment]
Absolutely :tada: Thanks for contributing, @M-ZubairAhmed!

**Comment by M-ZubairAhmed** [comment]
Hi @mickmister i was just informed that Larkox is working on this one as per https://github.com/mattermost/mattermost-plugin-github/issues/127 efforts, please assign it to him

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-github/issues/127
