### ISSUE TITLE
Include comments in notifications for approval / changes requested

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#152]
#### Summary

When a PR receives an approval or changes are requested, and the reviewer left a comment with their review, the comment is not shown in the MM notification. It can work similarly to how the `commented on your pull request` notification works, where the comment is embedded in the post.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: GitHub" community channel](https://community.mattermost.com/core/channels/github-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by enolal826** [comment]
I'd like to work on this!

**Comment by hanzei** [comment]
Awesome, thanks @enolal826 :+1:
