### ISSUE TITLE
Wrong emoji rendered in new issue notification

### ISSUE THREAD

**Issue by maruTA-bis5** [mattermost/mattermost-plugin-github#156]
[This issue](https://github.com/excella-core/excella-pdfexporter/issues/16) has 🙅‍♂ (`:no_good_man`) and 🙆‍♂ (`:ok_man:`) emojis.
But rendered as this: 
![image](https://user-images.githubusercontent.com/1310661/68915839-026f4180-07a7-11ea-985e-a99f4d82105d.png)

Environment:
- Mattermost Server: 5.16.2
- GitHub Plugin: 0.11.0 (prepackaged)
- OS: Windows 10 Pro 1809
- Browsers: Firefox Developer Edition 71.0b9, Desktop App 4.3.1, Google Chrome 78.0.3904.97

**Comment by levb** [comment]
This seems like a general issue with Mattermost Markdown, logged as https://mattermost.atlassian.net/browse/MM-20676 for the platform to fix.
