### ISSUE TITLE
GitHub plugin has no validation if subscribing with an invalid feature 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#165]
If you try and subscribe to a repo with an invalid feature, The ephemeral post tells you the subscription was successful but nothing will be delivered as the feature does not exist.

Can we validate when a feature does not exist to prevent user error

Steps:
1. type  `/github subscribe DHaussermann/hello-world create` (the 's' is missing)
**Observed** `Successfully subscribed to hello-world.`
**Expected**: `create` is not a valid feature

**Comment by aayush-plivo** [comment]
@levb I'd like to take this up.

Approach: Add validation for feature here: https://github.com/mattermost/mattermost-plugin-github/blob/23f77f082659e78f1d519eb3aacb0ceb94a3cc21/server/command.go#L142

**Comment by levb** [comment]
cc @jfrerich

**Comment by checkaayush** [comment]
PR for review: https://github.com/mattermost/mattermost-plugin-github/pull/183

**Comment by aayush-plivo** [comment]
The CI is failing in `make check-style`, which seems to be due to this issue: https://github.com/golang/go/issues/34053. Can someone help with this?

**Comment by checkaayush** [comment]
The CI is failing in `make check-style`, which seems to be due to this issue: https://github.com/golang/go/issues/34053. Can someone help with this?

**Comment by levb** [comment]
> The CI is failing in `make check-style`, which seems to be due to this issue: [golang/go#34053](https://github.com/golang/go/issues/34053). Can someone help with this?

Commented in the PR, need gofmt.

**Comment by aayush-plivo** [comment]
> > The CI is failing in `make check-style`, which seems to be due to this issue: [golang/go#34053](https://github.com/golang/go/issues/34053). Can someone help with this?
> 
> Commented in the PR, need gofmt.

Done.
