### ISSUE TITLE
Proposal: Add icon for build status on the open PRs

### ISSUE THREAD

**Issue by reflog** [mattermost/mattermost-plugin-github#167]
Maybe two icons, one red one green with a number. Clicking that icon will open LHS with the PRs that are either green or red

**Comment by hanzei** [comment]
@reflog Are you proposing to have two icon on the LHS or the RHS?

**Comment by reflog** [comment]
RHS, similar to the icons we already have, one for broken builds one for passed

**Comment by hanzei** [comment]
Maybe we should the icons right next to the name similar how GitHub does it
![Screenshot from 2019-12-22 20-40-41](https://user-images.githubusercontent.com/16541325/71326478-b927b580-24fb-11ea-8253-11f5a27cbc89.png)

![Screenshot from 2019-12-22 20-41-20](https://user-images.githubusercontent.com/16541325/71326463-749c1a00-24fb-11ea-8de4-65ae4548a654.png)

**Comment by reflog** [comment]
Grr. Sorry, I meant LHS for my icons. But your idea for RHS is great too. Not mutually exclusive :)
I meant something like (sorry for my amazing UI skills):
![image](https://user-images.githubusercontent.com/109876/71343961-f4f96400-2569-11ea-957e-3bb414317bd1.png)

**Comment by hanzei** [comment]
Good that talked about this :wink:

Actually, I would push back on adding this to the LHS. If a user is not part of a team, the icon is shown under the username. But there isn't enough space for more icon. 
![Screenshot from 2020-01-08 14-23-02](https://user-images.githubusercontent.com/16541325/71981358-8cc1a800-3222-11ea-9d6b-c66d27e6ef16.png)


Hence, I propose to only show an icon next to the PR name on the RHS. Let me know what you think @reflog.

**Comment by reflog** [comment]
That definitely makes sense. I didn't consider the horizontal layout

**Comment by jfrerich** [comment]
@hanzei, @reflog Correct me if wrong, but the RHS implementation was merged in this PR https://github.com/mattermost/mattermost-plugin-github/pull/170.  Assuming LHS will be left alone, can we close this issue?

**Comment by hanzei** [comment]
Good catch @jfrerich, closing
