### ISSUE TITLE
Remove comments before posting a notification

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#171]
When e.g. a PR gets created and the PR description contains a md comment, GitHub will ignore the content of the comment and don't render it. However, Mattermost doesn't understand Markdown comments and will show the content in the comment.

This issue is about fixing this by removing all comments before posting a message to Mattermost.

**Comment by M-ZubairAhmed** [comment]
Can i work on this

**Comment by hanzei** [comment]
Awesome, thanks @M-ZubairAhmed!
