### ISSUE TITLE
Links in todo messages should be consistent, include repo info

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-github#178]
The output of /github todo lists PRs, and assignments differs from that of Messages.

![image](https://user-images.githubusercontent.com/1187448/72808288-1f444d00-3c0e-11ea-9482-a3ddcebee6d4.png)

1. They should be consistent
2. They should include both the repo reference, and the PR title.
3. bonus: Unread messages should indicate if PR or Issue

Suggested format: `[org/repo-last-token-ellipsis](repoURL)[PR/IssueID title](issueURL)`
The repo name should be parsed, and shortened to its last word, with an ellipsis prepended if truncated. The title should probably be truncated at say 256 characters, just in case?

example:
-----
### Unread Messages
You have 8 unread messages:
* [mattermost/...server](https://github.com/mattermost/mattermost-server/issues/10438) [**#10438** Rewrite existing plugin API tests to exclusively test via actual plugin](https://github.com/mattermost/mattermost-server/issues/10438)
...
### Review Requests
You have 1 pull requests awaiting your review:
* [mattermost/...zoom](https://github.com/mattermost/mattermost-plugin-zoom) [**#45** Added webhook info](https://github.com/mattermost/mattermost-plugin-zoom/pull/45)
### Your Open Pull Requests
You have 2 open pull requests:
...

**Comment by levb** [comment]
cc @aaronrothschild @asaadmahmood for copy/formatting suggestions

**Comment by aaronrothschild** [comment]
Bonus Bonus: I will go on a limb and say that it may be useful to GROUP the messages/issues/PRs within the sections by repo (IF there is >1 issue/PR for that repo in the list).  

@levb @asaadmahmood Curious if you think it would help to present these in a tabular format?

**Comment by levb** [comment]
-1 for tables, they consume too much space.

**Comment by aayush-plivo** [comment]
@levb I'd like to give this a shot.

**Comment by checkaayush** [comment]
I'd like to take this up.

**Comment by levb** [comment]
@checkaayush go for it! A personal thank you if you get it done!

**Comment by aayush-plivo** [comment]
@levb In the suggested format `[org/repo-last-token-ellipsis](repoURL)[PR/IssueID title](issueURL)`, if the title is going to be a hyperlink, isn't the PR/IssueID before it redundant?

I'd like to suggest the following:

- For unread messages:
  - `[org/repo-last-token-ellipsis](repoURL) <type> [title](issueURL)`
  - `type` above will be either `PR` or `Issue`
  - Example: 
    - [mattermost/...server](https://github.com/mattermost/mattermost-server) Issue [Rewrite existing plugin API tests to exclusively test via actual plugin](https://github.com/mattermost/mattermost-server/issues/10438)

- For other categories:
  - `[org/repo-last-token-ellipsis](repoURL) [title](issueURL)`
  - Example:
    - [mattermost/...server](https://github.com/mattermost/mattermost-server) [Rewrite existing plugin API tests to exclusively test via actual plugin](https://github.com/mattermost/mattermost-server/issues/10438)

If we want overall consistency at the cost of some redundancy, we can even use the format picked for unread messages and apply it in all other categories. 

Suggestions? @aaronrothschild

**Comment by checkaayush** [comment]
@levb In the suggested format `[org/repo-last-token-ellipsis](repoURL)[PR/IssueID title](issueURL)`, if the title is going to be a hyperlink, isn't the PR/IssueID before it redundant?

I'd like to suggest the following:

- For unread messages:
  - `[org/repo-last-token-ellipsis](repoURL) <type> [title](issueURL)`
  - `type` above will be either `PR` or `Issue`
  - Example: 
    - [mattermost/...server](https://github.com/mattermost/mattermost-server) Issue [Rewrite existing plugin API tests to exclusively test via actual plugin](https://github.com/mattermost/mattermost-server/issues/10438)

- For other categories:
  - `[org/repo-last-token-ellipsis](repoURL) [title](issueURL)`
  - Example:
    - [mattermost/...server](https://github.com/mattermost/mattermost-server) [Rewrite existing plugin API tests to exclusively test via actual plugin](https://github.com/mattermost/mattermost-server/issues/10438)

If we want overall consistency at the cost of some redundancy, we can even use the format picked for unread messages and apply it in all other categories. 

Suggestions? @aaronrothschild

**Comment by levb** [comment]
@checkaayush I like your suggestion. It may be a good idea to post this for discussing in the Plugin: GitHub channel on community - I expect more opinions on the matter.

**Comment by aaronrothschild** [comment]
> @checkaayush I like your suggestion. It may be a good idea to post this for discussing in the Plugin: GitHub channel on community - I expect more opinions on the matter.

@checkaayush Agree with Lev, I will take any developer suggestions over mine :)

**Comment by aayush-plivo** [comment]
I'm going ahead with development as per my suggestion here: https://github.com/mattermost/mattermost-plugin-github/issues/178#issuecomment-585133677. 

I'll extract the message formatting logic in a separate function so that changing (and testing) it as desired becomes trivial.

**Comment by checkaayush** [comment]
I'm going ahead with development as per my suggestion here: https://github.com/mattermost/mattermost-plugin-github/issues/178#issuecomment-585133677. 

I'll extract the message formatting logic in a separate function so that changing (and testing) it as desired becomes trivial.

**Comment by asaadmahmood** [comment]
I agree with @levb. Tables take too much space.

**Comment by checkaayush** [comment]
Assumptions I'm making during development:

- Trimming title to 80 characters with ellipsis as suffix.
- Repository names, when having multiple words, will be separated by hyphens `-`.

If any of the assumptions seem inappropriate, let me know.
