### ISSUE TITLE
Results from /github subscribe list should be ordered

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#180]
Currently, the results returned from `/github subscribe list` get returned in a random order. The should be ordered by the repo name instead.

**Comment by bakurits** [comment]
I would like to work on this

**Comment by hanzei** [comment]
Thanks @bakurits :+1:

**Comment by hanzei** [comment]
@bakurits How are you doing with this ticket? Do you have any questions?

**Comment by bakurits** [comment]
> @bakurits How are you doing with this ticket? Do you have any questions?

Yes, I am. I'm done I think, but can't test it. Do you have any suggestions?

**Comment by hanzei** [comment]
You could move your logic for creating a the list of subscriptions into from https://github.com/mattermost/mattermost-plugin-github/blob/9a40ca24e3d9ea9edd2c20079cfe1a9a10208f2a/server/command.go#L157-L164 to `server/subscriptions.go` and then set up a unit test at `server/subscriptions_test.go`. Could this work for you?

**Comment by bakurits** [comment]
I'm on it

**Comment by bakurits** [comment]
@hanzei 
I think I have to mock GetSubscriptions() method here. [https://github.com/mattermost/mattermost-plugin-github/blob/9a40ca24e3d9ea9edd2c20079cfe1a9a10208f2a/server/subscriptions.go#L148](url)
Is there any other way?
