### ISSUE TITLE
Display time of notification in the Unread Messages pane

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#182]
#### Summary

The notifications in the Unread Messages are currently ordered with most recent on top, but it would be useful to know when each notification was created, like it shows in the GitHub UI.

#### Screenshots

![image](https://user-images.githubusercontent.com/6913320/73561690-707ee880-4427-11ea-8b0d-817f81d610ab.png)

![image](https://user-images.githubusercontent.com/6913320/73561780-a6bc6800-4427-11ea-9f9b-ea01cc55cc2a.png)

**Comment by rakhi2104** [comment]
I want to take this up

**Comment by mickmister** [comment]
@rakhi2104 Great, thank you!

**Comment by hanzei** [comment]
Hey @rakhi2104,

I just wanted to touch bases and check, if you are still working on this issue.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-github/pull/463
