### ISSUE TITLE
Don't try to print review body if it's empty

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#185]
https://github.com/mattermost/mattermost-plugin-github/pull/153 added support for including the review comment in the notification.

But if there wasn't any message within the review only `>` is shown. 

![Screenshot from 2020-02-05 16-16-39](https://user-images.githubusercontent.com/16541325/73854749-45373780-4833-11ea-8c9d-ae46f389f26a.png)

This issues is about not showing `>` if there is no message.

**Comment by vespian** [comment]
I'll like to take this one.
