### ISSUE TITLE
Result for /github subscribe list should show flags

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#186]
Currently only features are shown in the list. There should also be all flags listed e.g. `--exclude-org-member`.

**Comment by aayush-plivo** [comment]
I'd like to give this up.

**Comment by checkaayush** [comment]
I'd like to take this up.

**Comment by hanzei** [comment]
Awesome, thanks @checkaayush

**Comment by checkaayush** [comment]
Currently, `--exclude-org-member` is the only supported flag. Assuming there'll be more flags supported in the future, here's what I'd like to propose:

- When 1 or more flags are set:
  * `mattermost-server` - pulls,issues,creates,deletes - `--exclude-org-member,--another-flag`

- When no flag is set:
  * `mattermost-server` - pulls,issues,creates,deletes

**Comment by hanzei** [comment]
That is a great suggestion. Looking forward to the PR :+1:

**Comment by checkaayush** [comment]
> That is a great suggestion. Looking forward to the PR 👍

Here you go: https://github.com/mattermost/mattermost-plugin-github/pull/197!
