### ISSUE TITLE
Deployment does no longer work post 5.12

### ISSUE THREAD

**Issue by EugenMayer** [mattermost/mattermost-plugin-github#189]
Following the docs at https://github.com/mattermost/mattermost-plugin-github#development

```
plugin built at: dist/github-0.14.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   248  100   199  100    49   1442    355 --:--:-- --:--:-- --:--:--  1797
Installing plugin via API
OK.
```

But when opening the system console, i still have 0.11-prepackaged

**Comment by EugenMayer** [comment]
When i use the upload method in the system console
, it works. So maybe the deploy task is broken?

**Comment by levb** [comment]
@EugenMayer Do you see plugin deployment-related messages in the mattermost-server log? Also, do you have the username/password correctly configured to use an admin account in your environment?

**Comment by EugenMayer** [comment]
Credentials are correct for sure, i get a success message. I did not check the server logs since i deployed using the upload variant later on

**Comment by levb** [comment]
@EugenMayer I _think_ there maybe bugs (cover-my-face) in the `make deploy` implementation, I always keep my eye on the server log to be sure the plugin was deployed successfully. Can you please confirm?

**Comment by EugenMayer** [comment]
@levb it was a one time deployment for #108 and i'am not really working on the project right now, so i'am the wrong guy to test. For me it looked like very easy to reproduce. If not, close the issue and if i should work further on on the plugin and try this again, i will paste you the server logs.

**Comment by hanzei** [comment]
@EugenMayer Could you double check that `MM_SERVICESETTINGS_SITEURL` is set to the right URL?

**Comment by hanzei** [comment]
Closing this issue as it has been stale for some time.
