### ISSUE TITLE
The plugin does not send me any message

### ISSUE THREAD

**Issue by avenkatach** [mattermost/mattermost-plugin-github#19]
Hi All,

I have configured everything on our enterprise github and mattermost environment (both launched internally) using the link below:

https://github.com/mattermost/mattermost-plugin-github

 but i am not getting notified for any changes on repos in my organization. Please let me know if you need any logs to troubleshoot the issue.
---Ajay

**Comment by jwilander** [comment]
Can you check the logs on your GitHub webhook and see if it's making requests successfully and returning 200s from Mattermost?

**Comment by jwilander** [comment]
If you could also provide the plugin configuration settings (sanitized of course) that would help

**Comment by jwilander** [comment]
Closing as stale
