### ISSUE TITLE
Unable to activate plugin

### ISSUE THREAD

**Issue by karlduderstadt** [mattermost/mattermost-plugin-github#204]
I have Mattermost Team Edition version 5.7.1. The GitHub plugin was not installed, so I downloaded it and installed it (v 0.13.0) using the system console in the browser (after enabling plugin uploads). The plugin then shows up in the list, but it fails to activate. The log reports the following error:

{"level":"error","ts":1583839143.495255,"caller":"app/plugin.go:97","msg":"Unable to activate plugin","plugin_id":"github","error":"plugin requires Mattermost 5.12.0: github"}  

The mattermost was installed together with gitlab. I am not sure if that is a problem.

**Comment by JtheBAB** [comment]
@karlduderstadt 

You are using a too old Mattermost version. As it writes here:

`{"level":"error","ts":1583839143.495255,"caller":"app/plugin.go:97","msg":"Unable to activate plugin","plugin_id":"github","error":"**plugin requires Mattermost 5.12.0**: github"}`

Either you update or use [this version](https://github.com/mattermost/mattermost-plugin-github/releases/tag/v0.9.2)

**Comment by karlduderstadt** [comment]
Yes that is very obvious :) 

Thanks for your fast response!!
