### ISSUE TITLE
Setting --exclude-org-member flag should fail when organization is not locked to reflect the functionality

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#214]
When stetting `--exclude-org-member` the subscription should fail if the the plugin config is not locked to an org. 

The way the functionality currently works - the flag looks at the Org in the config and not simply any subscription you put in place. This can cause confusion if someone who does not have the org locked tries to use the flag.  Therefore, if you have the Org unlocked and subscribe to anything using the flag, you should see a validation message. 

Something like: _"Unable to set --exclude-org-member flag. The GitHub plugin is not locked to a single organization."_

**Comment by jrepe** [comment]
hey, mind if I have a go at this one?
