### ISSUE TITLE
Indicate if a PR has a conflict

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#225]
The new RHS contains a little check mark that indicates that all GH check are green. It would be handy if there is an indication for merge conflicts, so users can start resolving them soon.

@asaadmahmood @larkox Ideas on how this could look like?

**Comment by larkox** [comment]
This is how GitHub show it
![Screenshot from 2020-03-25 13-12-24](https://user-images.githubusercontent.com/1933730/77535177-75e23780-6e9a-11ea-9c43-7ee158739637.png)
How about the gray warning sign with a tooltip "merge required"?

**Comment by hanzei** [comment]
How would the gray warning sign look like?

**Comment by larkox** [comment]
Something like this:
![Screenshot from 2020-03-25 15-07-13](https://user-images.githubusercontent.com/1933730/77545246-74b90680-6eaa-11ea-89aa-fddd6a8caa14.png)
