### ISSUE TITLE
PRs for private repos in orgs not showing up under sidebar button

### ISSUE THREAD

**Issue by jwilander** [mattermost/mattermost-plugin-github#226]
### Summary
I have 4 pull requests open in private repos under the mattermost org but they don't show up in my sidebar:

<img width="124" alt="Screen Shot 2020-03-25 at 12 50 28 PM" src="https://user-images.githubusercontent.com/2672098/77563412-a2488480-6e97-11ea-8e17-2b1a7eb9d48e.png">

### Possible Cause

I believe it all stems from our search query here: https://github.com/mattermost/mattermost-plugin-github/blob/88d28a4d9dfc78fcec41256799083c029aef4010/server/utils.go#L28

I think one issue is that we're not pre-pending the org with `org:` in the search.

The other issue seems to be how wonky the GitHub search results are. For example, if I search for all my open PRs it doesn't include private repos from orgs by default:

<img width="1024" alt="Screen Shot 2020-03-25 at 12 48 39 PM" src="https://user-images.githubusercontent.com/2672098/77563786-18e58200-6e98-11ea-8e12-0dfe3f74b741.png">

Or if I search for private open PRs it doesn't show the ones from orgs:

<img width="1007" alt="Screen Shot 2020-03-25 at 12 48 51 PM" src="https://user-images.githubusercontent.com/2672098/77563887-40d4e580-6e98-11ea-8977-5bfd75eaf0e5.png">

But if I just include the `org:` qualifier it does show the private PRs from the org:

<img width="1017" alt="Screen Shot 2020-03-25 at 12 48 23 PM" src="https://user-images.githubusercontent.com/2672098/77563935-53e7b580-6e98-11ea-89fd-9b41a94978fa.png">

### Possible Solution

To fix the org scoped case I think we just need to include the `org:` prefix in the search query.

To fix the non-org scoped case we'd have to do more work and possibly make multiple searches for all the orgs the user is in.

**Comment by hanzei** [comment]
@jwilander Are you encountering this issue on Community? Did you run `/github connect private` and re-connected your account?

**Comment by jwilander** [comment]
Yes, this after running `/github connect private`. I even did a full disconnect and reconnect to confirm

**Comment by jwilander** [comment]
Ok I re-connected it again and it seems to no longer be an issue. Might have just been an issue connecting my account because of the multi-server nature of commuinty.mattermost.com. Closing for now and if I see it again I'll open it up.

**Comment by hanzei** [comment]
I can't repo your issue with the GH search. Both an issue and a PR show up in the search 
![Screenshot from 2020-03-27 09-15-23](https://user-images.githubusercontent.com/16541325/77735883-9bdb1980-700b-11ea-841d-e4ec99f656bb.png)

But I can repo your issue with the PRs not showing up on the RHS locally. I suppose that is because my local oauth app has no access to the `mattermost` org.

On community it works fine.
![Screenshot from 2020-03-27 09-18-32](https://user-images.githubusercontent.com/16541325/77736052-f2e0ee80-700b-11ea-9e47-cdb3b83f5fc7.png)

Are these screenshots for community?

**Comment by hanzei** [comment]
Note to self: Refresh browser page before writing an answer
