### ISSUE TITLE
Handle todo message with very long connected text.

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-github#227]
When a user has a message with very long text with no spaces, the text scrolls to the right. 

This an edge case that probably isn't going to be common but should be addressed.  

Looking at the image
1) very long text with scrolling issue (needs solution)
2) very long text with wrapping (correct)
3) very long HTML link that wraps correctly
![image](https://user-images.githubusercontent.com/7575921/77564682-1b90a900-6e91-11ea-8d4f-bd381c3fdfdb.png)

**Comment by marianunez** [comment]
Should this be in the Todo Plugin repo?

**Comment by jfrerich** [comment]
😆 @marianunez yes.  Moving now.

**Comment by jfrerich** [comment]
wrong repo.  Should be in todo plugin
