### ISSUE TITLE
[Feature Branch - Create Issue Modal] - Add GitHubRepoSelector component to the Attach Comment Modal

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-github#233]
### Summary
**Requires that https://github.com/mattermost/mattermost-plugin-github/pull/232 be merged first.**  Or work based on the branch in the PR https://github.com/mattermost/mattermost-plugin-github/tree/GH-218-filter-repos.

The current implementation of the attach comment to issue modal does not have a component to reduce available issues by repo.  The user can search for text that includes the repo name, but adding this component will allow filtering only on issues in a specific library.

### PR against the `Feature-create-issue-modal` feature branch

This issue exists in a feature branch, not master.

To work on this issue:
* mention in this ticket that you would like to take the issue
* create a branch from the `FEATURE-create-issue-modal` branch https://github.com/mattermost/mattermost-plugin-github/tree/FEATURE-create-issue-modal
* submit PR against `FEATURE-create-issue-modal`

**Comment by hanzei** [comment]
@jfrerich Is this ticket resolved?
