### ISSUE TITLE
Update webapp code to use `id` from manifest.js

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-github#238]
Currently, the pluginId value is hardcoded in many places, using `state['plugins-github']`.

This ticket request is to replace all occurrences with `plugins-${id}`

**Comment by bakurits** [comment]
I would like to work on that

**Comment by jfrerich** [comment]
Wow! 2 minutes after posting :) Sure, it is yours, @bakurits.

**Comment by bakurits** [comment]
@jfrerich wouldn't it be better to call this variable `pluginId` and not `id`?
for example here
```javascript
const id = ownProps.user ? ownProps.user.id : '';
const user = state['plugins-github'].githubUsers[id] || {};
```
id is already declared

**Comment by jfrerich** [comment]
@bakurits, I agree that pluginId would be more appropriate.  Please use that naming convention!
