### ISSUE TITLE
Add aria-labels to RHS elements

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#241]
I've noticed that the different elements/icons in the RHS PR list view do not have any aria-labels, so hovering over them has no effect. Some examples can be seen in this screenshot, particularly the PR link and the build status icon.

![image](https://user-images.githubusercontent.com/6913320/79371859-099ba680-7f23-11ea-9874-1a7a8a7bdf26.png)

**Comment by sanjaydemansol** [comment]
Hi @mickmister , I guess by
> hovering over them

you mean we need to add titles to icons, right?
<img width="245" alt="Screenshot_32" src="https://user-images.githubusercontent.com/85980820/126622970-821285a3-e0b5-4797-b03c-756220637745.png">
like that ?_(my tool didn't capture cursor)_

**Comment by mickmister** [comment]
@sanjaydemansol Using `title` sounds good
