### ISSUE TITLE
Use gorilla/mux as http router

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#246]
To unify http handling https://github.com/gorilla/mux should be used as a http router. The router should also be strict on the allowed http method.

**Comment by bakurits** [comment]
Do you mean `ServeHTTP` in `api.go`? I can do that.

**Comment by hanzei** [comment]
That is correct @bakurits. Thank you :+1:

**Comment by hanzei** [comment]
Bonus idea:
Extract the common code block https://github.com/mattermost/mattermost-plugin-github/blob/5997508eaf44a48b00cb9f97579c61bfe695db63/server/api.go#L101-L105 into it's own function with the signature: `(func(http.ResponseWriter, *httpRequest, userID)) http.HandlerFunc`

**Comment by bakurits** [comment]
@hanzei 
somethimes it's 
```go
writeAPIError(w, &APIErrorResponse{ID: "", Message: "Not authorized.", StatusCode: http.StatusUnauthorized})
```
and somethimes 
```go
http.Error(w, "Not authorized", http.StatusUnauthorized)
```
can I remove one of them? If I only use `writeAPIError` will there be any problem?
