### ISSUE TITLE
Unable to connect ("proxyconnect tcp: EOF")

### ISSUE THREAD

**Issue by wbaeck** [mattermost/mattermost-plugin-github#247]
Hi

We are running Mattermost 5.21 and want to use the gitlab plugin. _**I'm aware that this is the github plugin but the developer of the gitlab plugin didn't know a solution and redirected be here as the gitlab plugin is a fork of this. Hopefully someone can help me.**_

I followed all the steps from the readme and I'm able to have the Gitlab icon show up in Mattermost. When I click on it the authorization confirmation pops up. After selecting the "Autorize" button I get the following error message:
`Post https://{gitlab-server-url}/oauth/token: proxyconnect tcp: EOF`

I tried all different ways but just can't find a solution or at least a way to identify the issue. Checked the debug log of MM - but no other entries found there.

Please help me to solve this!

Thanks in advance

**Comment by hanzei** [comment]
This seams like an issue with your server setup. Could you manually `curl` the endpoint and see if you can hit it?

**Comment by wbaeck** [comment]
Thanks for your response.

I tried `curl` from the MM Server and this is the result:
`# curl https://{gitlab-server-url}/oauth/token`

```<html><body>You are being <a href="https://{gitlab-server-url}/users/sign_in">redirected</a>.</body></html>```

So for me it looks like our certificates and connections are working fine.

**Comment by wbaeck** [comment]
Finally I was able to solve this issue. 

It was a config issue. Because we configured an outbound proxy to access the Marketplace we had to exclude our internal gitlab server from this with "NO_PROXY" according to https://docs.mattermost.com/install/outbound-proxy.html.

But thanks for reply.
