### ISSUE TITLE
Attaching a message to an issue should link to GitHub account not MM account

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#253]
Instead of using the MM username the username on GitHub should be used. The user whose message gets links, might not be connected to GitHub. In this case fall to back the MM username.

![Screenshot from 2020-05-01 00-02-52](https://user-images.githubusercontent.com/16541325/80763766-8fcd0500-8b3f-11ea-86ae-9822f57273ce.png)

**Comment by abdulsmapara** [comment]
I am interested in resolving this issue.

**Comment by abdulsmapara** [comment]
Does it mean that whenever an issue is created (or a comment is made) on GitHub, the user getting the notification on MM should get the GitHub username and not the MM username?
I have a confusion as the image shown here is that of a GitHub comment (and not of MM channel message)

**Comment by hanzei** [comment]
Hi @abdulsmapara,

The ticket is about the the "Attach to issue" functionality, which you can find when clicking on the dot menu of a post. Is the ticket now more clear?
![Screenshot from 2020-05-04 12-47-02](https://user-images.githubusercontent.com/16541325/80959293-ce481580-8e06-11ea-95c5-4f2ea6d0c98b.png)

**Comment by abdulsmapara** [comment]
Ok! So it meant the "Attach to Issue" functionality of MM, thanks @hanzei for the clarification

So, is my understanding (as described below) for the ticket now clear ?
If a user X attaches a message from another user Y to a GitHub issue, X & Y's GitHub username should be used on the comment on GitHub and in case Y is not connected to GitHub on MM, Y's MM username is to be used.

**Comment by hanzei** [comment]
Exactly @abdulsmapara
