### ISSUE TITLE
Properly wrap errors

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#254]
Generally errors should be wrapped using [`Wrap`](https://pkg.go.dev/github.com/pkg/errors?tab=doc#Wrap) and [`Wrapf`](https://pkg.go.dev/github.com/pkg/errors?tab=doc#Wrapf). This ticket is about going trough the code base and adding error wrapping everywhere where it's appropriate.

_Originally posted by @bakurits in https://github.com/mattermost/mattermost-plugin-github/pull/252_

**Comment by dbejanishvili** [comment]
I would like to work on that

**Comment by hanzei** [comment]
Thanks @dbejanishvili. Let me know, if you have any questions.

**Comment by dbejanishvili** [comment]
https://github.com/mattermost/mattermost-plugin-github/blob/119ff1807a40eca316e5c1644589f056baa71936/server/subscriptions.go#L240

It seems that the error returned from KVSet is ignored here, is this intentional? If not, should I fix it?

**Comment by hanzei** [comment]
No, that error should not be ignore. Please fix it.

**Comment by bakurits** [comment]
> No, that error should not be ignore. Please fix it.

@hanzei don't you already resolved this in https://github.com/mattermost/mattermost-plugin-github/pull/252 ?
https://github.com/mattermost/mattermost-plugin-github/blob/0953348ee0956cd2478bfdbc97220f14a6261bc3/server/subscriptions.go#L243

**Comment by hanzei** [comment]
You have eagle eyes @bakurits! That is correct, but I hope #260 gets merged before my PR and I can easily resolve the merge conflict. :wink:
