### ISSUE TITLE
Add tooltip for pull request links

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#255]
Similar on how mousing over a link on github.com works there should be a tooltip for plugin to pull requests in the webapp. 

It should show:
- The repo
- The date where the PR was opened
- Title
- Number
- The first three labels

This is how a tooltip looks like on GitHub. Please note that some information that GitHub shows should not be part of the initial implementations to reduce complexity. 

![Screenshot from 2020-05-01 11-01-01](https://user-images.githubusercontent.com/16541325/80863706-5b139780-8c7e-11ea-9284-9530a44fa36d.png)

For more information on how to add tooltips to the webapp see https://github.com/mattermost/mattermost-webapp/pull/2386, which introduced support for it.

**Comment by hanzei** [comment]
@asaadmahmood Let me know if you have any concerns about copying the style from GitHub.

**Comment by asaadmahmood** [comment]
@hanzei Not much, some of the tooltips and alignments look off, but we can fix that when a PR is in.

**Comment by fedealconada** [comment]
I can take this one @hanzei

**Comment by hanzei** [comment]
That would be awesome, @fedealconada :tada:
