### ISSUE TITLE
Display labels applied on the issue/PR when the bot posts a new issue or PR

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#257]

**Comment by hanzei** [comment]
@mickmister Do you have ideas on who the labels should be shown? Would they be dynamically rendered and this would be a webapp only feature? Or generated and served by the server part and embedded via Markdown?

**Comment by mickmister** [comment]
@hanzei Ideally they would be generated with markdown, maybe rendered as code like `Tech/Go` `Help Wanted` within the post. No custom coloring etc.

**Comment by mickmister** [comment]
Displaying the assignee if present would be useful too.

These improvements are rendered nil if these values aren't applied upon issue creation, of course. Basically any value attached to the issue on GitHub

**Comment by Szymongib** [comment]
Hi, could I work on this one?

**Comment by mickmister** [comment]
Absolutely, thanks @Szymongib!

**Comment by Szymongib** [comment]
Thanks, @mickmister!
I have created a draft PR https://github.com/mattermost/mattermost-plugin-github/pull/335 with a few questions. I would really appreciate if you could take a look at those when you have a moment.
