### ISSUE TITLE
Don't try to autolink messages from bots

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#266]
When a message gets posted by a bot and `EnableCodePreview` is enabled, the plugin tries to get the GitHub token for that user, which fails. Use [`ShouldProcessMessage`](https://developers.mattermost.com/extend/plugins/server/reference/#Helpers.ShouldProcessMessage) to skip posts from bots and system messages.

**Comment by dbejanishvili** [comment]
I'll do this if it is still available

**Comment by hanzei** [comment]
All your's @dbejanishvili :+1:
