### ISSUE TITLE
Post a notification if issue gets reopened

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#267]
When a issue gets closed and then reopened, only a notification for closing the issue is send to a channel that subscribed to that repository. There should also be a notification saying that the issue got reopened. The wording should be:
`{{template "repo" .GetRepo}} Issue {{template "issue" .GetIssue}} reopened by {{template "user" .GetSender}}.`

**Comment by checkaayush** [comment]
Isn't this what this part of the code (https://github.com/mattermost/mattermost-plugin-github/blob/master/server/webhook.go#L878) does?

**Comment by hanzei** [comment]
@checkaayush That part of the code deals with the notification to a user, not to channels. Per user notifications for this event work fine.
