### ISSUE TITLE
Use official GitHub icons

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-github#268]
We are using a few SVGs under `webapp/src/images/icons` that correspond to the Github icons. These and other Github icons are published in a npm package (https://primer.style/octicons/). We should use this package instead of the SVGs on `webapp/src/images/icons`.

**Comment by AugustasV** [comment]
I would like to work on this issue!

**Comment by larkox** [comment]
Thanks @AugustasV ! It is yours.
If you need any help, feel free to ask.
Regarding tips, you can take a look to [this PR](https://github.com/mattermost/mattermost-plugin-github/pull/258). There the contributor added the npm package and used some icons from the package. Since it is already merged, you will not need to import the package again. Just use it on the right places.

**Comment by AugustasV** [comment]
Great! @larkox Made changes according Octicons plugin documentation, not sure if it's correct - didin't know how to test it.
