### ISSUE TITLE
"Changes requested" icon is unreadable in dark themes

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#270]
On the Github plugin RHS, under the "Your open pull requests" section, the PRs with changes requested have a red icon next to the number of reviews completed. The color makes the icon unreadable on dark themes:

 
![image-2020-05-04-13-06-27-085](https://user-images.githubusercontent.com/16541325/81924275-32c15c80-95df-11ea-8dac-8171a17e8fd9.png)

The milestone icon is also a bit hard to read:

![image-2020-05-04-13-07-23-475](https://user-images.githubusercontent.com/16541325/81924285-3654e380-95df-11ea-9ba4-550a6e62dc36.png)

**Comment by hanzei** [comment]
Moved this issue from JIRA to GitHub:https://mattermost.atlassian.net/browse/MM-24768

**Comment by hanzei** [comment]
@asaadmahmood Not urgent: I'm wondering what you thoughts are on this issue. Maybe invert the color of the milestone icon?

**Comment by asaadmahmood** [comment]
@hanzei yup, we should just use the theme color (centerChannelColor) for the fill of that svg.

**Comment by hanzei** [comment]
@asaadmahmood With your requested changes it looks like this:
![Screenshot from 2020-08-19 11-09-00](https://user-images.githubusercontent.com/16541325/90615450-6f1edd00-e20c-11ea-99d3-0db2a373e15e.png)

Is this correct?

**Comment by asaadmahmood** [comment]
@hanzei Apologies, I meant for the flag.
![Screenshot 2020-08-19 at 2 14 21 PM](https://user-images.githubusercontent.com/11034289/90616007-4efc1780-e226-11ea-83f6-93455947404f.png)

For the changes requested icon, I would prefer if it we use the away Icon status theme color, and then when the reviews are done, we use the online status icon theme color.

**Comment by hanzei** [comment]
@asaadmahmood How does this look to you?

![Screenshot from 2020-08-19 12-20-11](https://user-images.githubusercontent.com/16541325/90623117-587d8380-e216-11ea-8949-a8a4c72d1f54.png)
![Screenshot from 2020-08-19 12-20-08](https://user-images.githubusercontent.com/16541325/90623118-59161a00-e216-11ea-9cf2-2763e357590d.png)
![Screenshot from 2020-08-19 12-19-55](https://user-images.githubusercontent.com/16541325/90623119-59aeb080-e216-11ea-82d4-a0c88d97e496.png)
![Screenshot from 2020-08-19 12-19-50](https://user-images.githubusercontent.com/16541325/90623121-59aeb080-e216-11ea-9a43-129745c6faf4.png)

**Comment by asaadmahmood** [comment]
@hanzei Is there an opacity on the icon (or the whole div that it is contained in)?

**Comment by hanzei** [comment]
@asaadmahmood No
