### ISSUE TITLE
In RHS, link to specific event that caused a notification when clicking on a notification

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#272]
Currently, clicking on a link in the `Notifications` RHS view brings you to the issue/PR that is associated with the notification. We could instead link to the new comment that caused the notification. This should be feasible if the notification itself contains the link to the specific event that caused the notification.

**Comment by aidapira** [comment]
Hi @mickmister, I have successfully replicated this issue and am working on resolving it.

**Comment by mickmister** [comment]
Great, thanks @aidapira!
