### ISSUE TITLE
GitHub info on LHS and post menu options are not visible until  

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#276]
When a connected user first logs in from a Mattermost client, the GitHub options for PRs, Messages, Issues etc... as well as post menu option are not visible until the user refreshes the client.

This occurs on browser as well as desktop.  
This does not seem to be a regression from the 0.14.0 release
![GitHubMisisng](https://user-images.githubusercontent.com/35588783/82346921-0afa3c00-99c5-11ea-988e-b1648362e57a.gif)

- Enable the plugin
- Login as a test user and connect your GitHub account
- Note GitHub options appear
- As the test user log in from a new browser session 
**Observed**: GitHub items and post menu options are not displayed
**Expected**: GitHub otions are shown in the UI
- Refresh the client
**Observed**: GitHub items are displayed normally.

**Comment by DHaussermann** [comment]
@aaronrothschild Given there is an imminent release for GitHub and we just hat triage today - Can you advise on the priority issue.

cc @hanzei if possible can you give a very high estimate of scope to help guide the priority decision.

**Comment by hanzei** [comment]
The plugin only checks if a user account is connected on a page refresh or a reconnect. https://github.com/mattermost/mattermost-plugin-github/blob/b124fd0e5d6a2fa70c4cf29c4edaf7bc8ad163cf/webapp/src/index.js#L25

I'm not sure how feasible it to only fetch that information if the user is connected. @larkox Can you help?

**Comment by larkox** [comment]
This should be already handled. The "connected" handler of the OAuth, apart of sending the DM with all the info (Welcome to Mattermost Github Plugin!...) sends a message through the websocket to make the client aware of the connection.

This is handled by the client, who should update everything.

All being said, all pieces are in place already. There must be some bug somewhere there.

**Comment by larkox** [comment]
@DHaussermann Have you noticed any error be it in webapp console or server just after the connect takes place? Do you receive the bot welcome message?

**Comment by aaronrothschild** [comment]
If this has been behavior for a while, we can ship.  Otherwise if a regression, let's fix it.  We said in the newsletter Github update would be available in the marketplace this week, ideally we can keep to that.

**Comment by hanzei** [comment]
This issue also happens in `v0.14.0` hence it's not a regression. Let's move to out of `v1.0.0`.

**Comment by hanzei** [comment]
@larkox This gist here is that the scenario starts while the user is not logged in. Hence the the connected handler correctly reports that there is no connected user, but never corrects itself, after the user logs in.
