### ISSUE TITLE
Allow picking labels in Create Issue dialog

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#277]
In the Create Issue dialog allow the users to pick a set of labels wich which will be attached to the issue on creation.

**Comment by hanzei** [comment]
@asaadmahmood Is there a component that can be reused? Maybe the Direct Message member picker?
![Screenshot from 2020-05-19 18-52-04](https://user-images.githubusercontent.com/16541325/82354976-dce71d00-9a01-11ea-9c70-ea1b87cb9069.png)

**Comment by asaadmahmood** [comment]
Yup, we should be able to use `react-select`.

**Comment by mickmister** [comment]
I also request to be able to pick assignee and milestone in the modal

**Comment by utkuufuk** [comment]
I'll take this one.

@mickmister @hanzei I have a question about this though:
> I also request to be able to pick assignee and milestone in the modal

How do we want to handle the cases where the given label, assignee, or milestone aren't defined in the target repository? 

I just manually tested the GitHub API. While you can create new labels on the fly, the request fails if the assignee (contributor) and/or the milestone are not defined. 

For instance, here's how the response looks like if the assignee (octocat) is invalid:

```json
{
  "message": "Validation Failed",
  "errors": [
    {
      "value": "octocat",
      "resource": "Issue",
      "field": "assignees",
      "code": "invalid"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/issues/#create-an-issue"
}
```

Certainly, there are ways to work-around this problem (e.g. by pre-fetching the available assignees & milestones and performing validation on the frontend based on those), but I feel like it could expand the scope of this issue quite a lot. 

That said, I don't mind doing all this in one PR if you think expanding the scope wouldn't be too much of a problem, or if somebody has a simpler solution in mind.

**Comment by utkuufuk** [comment]
@hanzei @mickmister I've examined the GitHub API reference a bit more and found out that milestones have to be specified by their IDs while creating an issue:
- https://docs.github.com/en/rest/reference/issues#create-an-issue
- https://github.com/google/go-github/blob/259aa56b9e3f43b924520fb5b5bc0784a901f90d/github/issues.go#L86

So, we can just type label & assignee **names** into the "create issue" dialog, but we cannot do the same for milestones.

For instance, we have a milestone called `v5.26.0` in the `mattermost-server` repository:
https://github.com/mattermost/mattermost-server/milestone/62

If you look at the URL, you can see that its ID is `62`. We should set that ID in the HTTP POST request if we want to associate the new issue with this milestone, whereas we can just pass label names & assignee names in the form of arrays of strings.

Therefore, if we want to allow users to select a milestone in the "create issue" dialog, we'll have to:
1. pre-fetch available milestones for the current repo (keep fetching as the user changes the repo selection)
2. keep track of a name-to-ID map of all milestones for the selected repo
3. allow the user to pick a milestone by name within the dialog
4. pass the ID of the selected milestone while making the API request

Please let me know your thoughts on how we should scope this issue in the light of this new (at least for me 😄) piece of information.

**Comment by mickmister** [comment]
@utkuufuk Having to type assignees and labels by hand is error-prone, and would not be a good experience for the user. I personally think fetching the values for each category is part of this task. It is probably a good idea to consolidate each type of entity being fetched into one React component, then having a wrapper component for each entity (labels, assignees etc).

I've done something similar in the Jira plugin. Here's an example of the consolidated [BackendSelector](https://github.com/mattermost/mattermost-plugin-jira/blob/8a6eb97e010afb9ddbf548112a749a50e60b65a2/webapp/src/components/data_selectors/backend_selector.tsx) component I've made there, as well as a [usage](https://github.com/mattermost/mattermost-plugin-jira/blob/8a6eb97e010afb9ddbf548112a749a50e60b65a2/webapp/src/components/data_selectors/jira_autocomplete_selector/jira_autocomplete_selector.tsx#L51-L56) of the component:

```jsx
<BackendSelector
    {...this.props}
    name={'epic'}
    fetchInitialSelectedValues={this.fetchInitialSelectedValues}
    search={this.searchAutoCompleteFields}
/>
```

I think it's appropriate to migrate the `BackendSelector` component over to the GitHub plugin. The code is intentionally generic so it should be able to be copy&pasted over here. We currently do not have a system set up to share components among the different plugins. If you need help with this, you can comment here, or DM me on https://community.mattermost.com at `michael.kochell`.

Please let me know your thoughts on this. Thanks for taking a look at this @utkuufuk!

**Comment by utkuufuk** [comment]
@mickmister Thank you for the clarification. I think there's a similar component in this plugin too: https://github.com/mattermost/mattermost-plugin-github/blob/master/webapp/src/components/react_select_setting.jsx

The problem is, retrieving labels is a bit tricky with our [GitHub API client](https://github.com/google/go-github). I examined the source code of the client library, and as far as I was able to see, it only lets us **search** for labels in a repository but it doesn't let us **fetch** all the available labels.

On the other hand, the GitHub API itself has an endpoint to fetch labels for a given repo:
https://docs.github.com/en/rest/reference/issues#list-labels-for-a-repository

That's why I had to implement my own mechanism for interactively fetching the labels as the user types into the selector widget. You can see my current implementation here: https://github.com/mattermost/mattermost-plugin-github/pull/343. I also commented on the relevant parts of the code with more detailed explanations, which you can also see on the PR page.

Please let me know what you think. I'm definitely open to any suggestions if you have a more efficient solution in mind.

**Comment by utkuufuk** [comment]
@mickmister Thank you for the clarification, I've sent you a DM on the community server.
