### ISSUE TITLE
 Unable to create subscriptions to private repos unless I have used `/github connect private` 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#284]
Creating a subscription to private repos requires `/github connect private` even when private repos is allowed. This may not necessarily be a bug but, the `/github connect private` functionality must be documented

Steps
- Configure the plugin to allow private repos  
- Login as a privileged user and connect to github using `/github connect` (not connect private)
- Attempt to create a subscription to a private repo where test user has permissions

**Expected**: Subscription successful
**Observed**: Unable to find repository

**Comment by hanzei** [comment]
I don't consider this a bug.

`/github help` stated:
> `private` is optional. If used, the github bot will ask for read access to your private repositories. If these repositories send webhook events to this Mattermost server, you will be notified of changes to those repositories.

Should this help text be more clear on how subscriptions to private repos work?

**Comment by DHaussermann** [comment]
@hanzei Maybe I'm not looking in the correct branch. Can you please link me to where the text you quoted is documented?

**Comment by hanzei** [comment]
@DHaussermann This text is reported when a user enters `/help text`: https://github.com/mattermost/mattermost-plugin-github/blob/b1e3667dc7e6823e22df1ba7eeb180fbcdc36b61/server/command.go#L15

**Comment by DHaussermann** [comment]
Thanks @hanzei 
This issue can be closed. The feature is working as documented.
