### ISSUE TITLE
Isolated case where user incorrectly appears connected to GitHub

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#286]
I'm seeing an isolated case where the user is not properly connected to GitHub  but the UI appears to show the user as connected. 

When trying to use the plugin several pieces of functionality break. I don't how the user arrived in this state. It persists after logout / login 

![Attach-Breaks](https://user-images.githubusercontent.com/35588783/82866290-9bb9a600-9ef6-11ea-8a13-f9334332c4ba.PNG)
![Capture2](https://user-images.githubusercontent.com/35588783/82866295-9cead300-9ef6-11ea-8a98-f9f9014d1d50.PNG)

**Comment by hanzei** [comment]
@DHaussermann is it possible that there was an outage at GitHub? The error message you posted get's generated when API calls to GitHub fail. Could you please also post the server logs? They contain the "real" error messages returned from GitHub.

**Comment by DHaussermann** [comment]
@hanzei to clarify this is continuously reproducible for this user. The user seems to be in the wrong state where they are not connected to GitHub. They are just seeing the UI as if they were connected. The related logs reflect that the user is not connected.
```
{"level":"error","ts":1590555300.112742,"caller":"mlog/sugar.go:23","msg":"error in getting user info","plugin_id":"github","error":"Must connect user account to GitHub first."}
{"level":"debug","ts":1590555300.8134468,"caller":"wsapi/websocket_handler.go:25","msg":"Websocket request","action":"user_update_active_status"}
{"level":"debug","ts":1590555303.0425446,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"snaxazyg7jyi3nib6i5nqcy7aw"}
{"level":"info","ts":1590555304.0335882,"caller":"go-plugin@v1.2.2/stream.go:15","msg":"{\"level\":\"error\",\"msg\":\"GET https://api.github.com/search/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Adkh-org+: 401 Bad credentials []\"}","plugin_id":"github","source":"plugin_stderr"}
```
Thoughts?

**Comment by hanzei** [comment]
Is it possible that you remove the GitHub plugin from your authenticated applications at https://github.com/settings/applications? Does re-connecting via `/github connect` fix the issue?

**Comment by DHaussermann** [comment]
Yes @hanzei I have no Idea how the how the 1 user got in this state but, diconnecting and reconnecting did resolve the issues. 

1 /5 We could close this and I can file an new issue if I see it occur again.
