### ISSUE TITLE
Apply user's theme to the link tooltip

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#294]
Currently the link tooltip is styled with a white background etc. It should instead match the user's theme to blend well with the center channel.

![Screenshot from 2020-06-04 18-01-01](https://user-images.githubusercontent.com/16541325/83865755-f046f780-a726-11ea-9c94-455c0c7d5736.png)

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/9ri6e1bpn7dqucrkdezxwgd3mw) *by @gabrieljackson*._

**Comment by hanzei** [comment]
@fedealconada Would you be interested in working on this given that you introduced the feature?

**Comment by fedealconada** [comment]
Sure @hanzei !

**Comment by fedealconada** [comment]
Hey @mickmister, I've linked the user's theme to the tooltip but there are some styles that are not passed in the theme's... I think that the things most affected are:
1. Box shadow of the tooltip
2. The little boxes specifying the repo branches (above `See more` link).

So, a couple of alternatives:
**Option 1**. We leave it like that (its not bad though).
**Option 2**. We add the `Menu__content` class to it, which will add some borders.
**Option 3**. We could add some additional classes to the theme but they could be a bit specific to the github tooltip

**Option 1**
![image](https://user-images.githubusercontent.com/4473536/84150339-1d9de900-aa38-11ea-89ec-86d1a5533469.png)
On the following image, note the Repo <- Repo in which there's not enough contrast between the light blues
![image](https://user-images.githubusercontent.com/4473536/84150314-124abd80-aa38-11ea-9069-057ba71ddf1f.png)
On the next two images, note the lack of box shadow (maybe not a big deal)
![image](https://user-images.githubusercontent.com/4473536/84150200-e8919680-aa37-11ea-818f-4c049b8cec2f.png)
![image](https://user-images.githubusercontent.com/4473536/84150278-07902880-aa38-11ea-836a-503a565923ea.png)


**Option 2**
On these images, I've added the `Menu__content` class. Note the rounded corners and the border color.
![image](https://user-images.githubusercontent.com/4473536/84149894-859fff80-aa37-11ea-82de-e81a1aefc96a.png)
![image](https://user-images.githubusercontent.com/4473536/84149936-93ee1b80-aa37-11ea-98bd-f3af6166cce6.png)
![image](https://user-images.githubusercontent.com/4473536/84149981-a10b0a80-aa37-11ea-959b-9dae8b5c585f.png)
![image](https://user-images.githubusercontent.com/4473536/84150016-ad8f6300-aa37-11ea-9125-546840613b40.png)

**Comment by hanzei** [comment]
@asaadmahmood What do you think about these ideas :point_up:

**Comment by asaadmahmood** [comment]
@fedealconada We can keep the box shadow black.
However, the border color of the tooltip can be: `center-channel-color-16`.
Also, can you increase the z-index of the tooltips to be `1070`?

**Comment by fedealconada** [comment]
hey @asaadmahmood, I've just added that. It would look like this:
![image](https://user-images.githubusercontent.com/4473536/84173575-daea0a00-aa53-11ea-885e-4e079912c414.png)
Thoughts?

**Comment by asaadmahmood** [comment]
@fedealconada Looks great to me, one thing though, add a `border-radius: 4px` to it as well.
