### ISSUE TITLE
Long branch names overflow in tooltip

### ISSUE THREAD

**Issue by reflog** [mattermost/mattermost-plugin-github#296]
![image](https://user-images.githubusercontent.com/109876/83963363-31b5df00-a8ae-11ea-8134-88ca8ff3ae21.png)

Background color seems to be conflicting and long labels overflow

**Comment by hanzei** [comment]
@reflog https://github.com/mattermost/mattermost-plugin-github/issues/294 encapsulates the theming issue. I've update this ticket to only target this overflow issue.

**Comment by hanzei** [comment]
For reference: https://github.com/mattermost/mattermost-server/pull/14756
