### ISSUE TITLE
Plugin Tooltip: Link to repo in heading instead of issue

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#297]
I also don't see the point of the "See More" link if we are already linking in the issue/PR title at the top of the card.

![image](https://user-images.githubusercontent.com/6913320/83995243-ebe92d00-a926-11ea-9536-688bcd001eb8.png)

**Comment by mickmister** [comment]
@asaadmahmood Any objections to making the repo name at the top link to the repo instead of linking to the issue/PR?

**Comment by asaadmahmood** [comment]
@mickmister That's fine.
Regarding the "See more", it makes sense in the overflowing context where things are being cropped off.

**Comment by mickmister** [comment]
@asaadmahmood The "See more" text shows even when the content is not overflowing. I also just realized that the `#### Summary` and `#### Ticket Link` bits are not visible. It seems there is quite a bit of work to be done on this.

**Comment by hanzei** [comment]
@mickmister Thanks for the report :+1: I've split up the ticket into two seperate bug reports and this ticket, which covers the improvements to `See More` and the repo link.
