### ISSUE TITLE
Link Tooltip does not work for links in RHS

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#302]
The white line seen in the screenshot is the left border of the tooltip's card. It is hidden behind the RHS. The z-index needs to be adjusted for the tooltip to take precedence over the RHS. I'm not sure if this is a change that needs to be applied to mattermost-webapp or to this plugin.

![image](https://user-images.githubusercontent.com/6913320/84084771-1af8b080-a9b2-11ea-97f0-769293f7c54b.png)

**Comment by hanzei** [comment]
@mickmister I an only confirm this bug on community-release and community-daily. Hence, it's a regression. Would you please open a JIRA for this?

**Comment by asaadmahmood** [comment]
@mickmister We should do this in the plugin.

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-webapp/pull/5712 will fix this
