### ISSUE TITLE
Unable to subscribe/receive notification from private repo in orgs

### ISSUE THREAD

**Issue by th-kwon** [mattermost/mattermost-plugin-github#306]
I'm just moving my repos into organization and found this problem - adding subscription of private repo inside organization makes error `unknown repositiory`. 

Making new repo causes same issue.
* Make new repo inside org with public and subscribe : succes
* Make new repo inside org with private and subscribe : fail
* Changing private repo to public and subscribe again : success, receives notification
* Change to private again and make notification : no notification

Github todo list also works wrong. Article from normal private repo is displaying fine but private repo inside org is not.

I got 6 assignments but github plugin shows only 5, excluding issues from private repo inside organization.
![image](https://user-images.githubusercontent.com/59942506/84239987-4efdde00-ab38-11ea-9d4e-6efa80add796.png)
![image](https://user-images.githubusercontent.com/59942506/84240147-8cfb0200-ab38-11ea-82ab-6f9561aaed1d.png)

**Comment by hanzei** [comment]
Did you connect your GitHub using `/github connect private`?

**Comment by th-kwon** [comment]
![image](https://user-images.githubusercontent.com/59942506/84332875-0cd0ad00-abc9-11ea-9b51-70ee5a12deef.png)
@hanzei Yeah that was my problem. Organization access was restricted by default. 

![image](https://user-images.githubusercontent.com/59942506/84333887-f2e49980-abcb-11ea-8da9-3431876c971e.png)
![image](https://user-images.githubusercontent.com/59942506/84333977-27585580-abcc-11ea-9754-1a5eae1ea0b3.png)
Granting access(or request access & approve) solved the problem. It must be done once except the organization itself makes the application.

Problem solved. Thanks for your help!

**Comment by hanzei** [comment]
Glad your issue got solved :+1:
