### ISSUE TITLE
Remove commented text in Tooltip link body

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#312]
Currently the link tooltip includes the contributing instructions in the body of the issue/PR. It is a bit noisy and doesn't convey the important information in the PR's description.

![image](https://user-images.githubusercontent.com/6913320/84585319-c5bb0580-addc-11ea-88e5-0da5666605b5.png)

**Comment by hanzei** [comment]
Let's go this server-side

**Comment by abdulsmapara** [comment]
I would like to give this a try.

**Comment by abdulsmapara** [comment]
I am thinking to use regular expressions for removing commented text inside `<!-- -->`.

**Comment by hanzei** [comment]
Thanks for taking a look @abdulsmapara.

Regular expressions are definitiv a valid approach to solve this issue.

**Comment by mickmister** [comment]
@abdulsmapara There was a PR that did this sort of fix for notifications. Could the same regex be used here?
https://github.com/mattermost/mattermost-plugin-github/pull/172
https://github.com/M-ZubairAhmed/mattermost-plugin-github/blob/ddab50ecf135f43ce6018fcab004aa9658f5ffbb/server/template.go#L13

**Comment by abdulsmapara** [comment]
@mickmister, I have exactly considered the same regex present in `template.go` to avoid redundancy.
