### ISSUE TITLE
Implement `/github issue create` to create a github issue with no post

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#313]
Currently you must use an existing post to create a GitHub issue from Mattermost. Following the method of creating an issue with no post in the Jira plugin, we can introduce a `/github issue create` slash command to open the Create Issue modal, with optional text passed into the command to prepopulate the issue's description.

`/github issue create`
and
`/github issue create Here's my issue title`

We would also need to remove the piece on the backend that adds a link back to the post in the issue description, and avoid the followup "Created an issue" post in the channel.

**Comment by hanzei** [comment]
Would it make sense to namespace this command in e.g. `/github issue create` to avoid collisions if e.g. creating a release is possible in the future.

**Comment by GodlikePenguin** [comment]
I'll take a look at this

**Comment by larkox** [comment]
Thanks @GodlikePenguin :tada:
