### ISSUE TITLE
The error message display in the Create Issue modal displays as JSON

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#318]
We should be displaying `e.message`, rather than the JSON representation of the error.

![image](https://user-images.githubusercontent.com/6913320/86401677-a9421880-bc78-11ea-8db7-a839a86ed79c.png)

**Comment by djanda97** [comment]
I will work on this.

**Comment by aidapira** [comment]
Hi @mickmister, I'm sorry I got too excited and submitted a PR for this issue before claiming it. I am very interested in this issue still. However, I need to make some changes to the current PR. I will be updating the PR with the new commits tentatively in a week or two.
