### ISSUE TITLE
Code Preview functionality may post private repos content

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-github#323]
Code Preview functionality add a preview of the files from github linked on the post. In order to get the information of the files, it uses the token of the poster. Therefore, any file the poster may link from a private repo, will be exposed by this functionality into the corresponding mattermost channel. This may be considered a breach on security, specially since there is no warning to the user that they are disclosing private information.

@jupenur Any thoughts on this?

**Comment by jupenur** [comment]
Well spotted @larkox. Seems like a minor security concern.

**Comment by hanzei** [comment]
@jupenur @asaadmahmood Do you have thoughts on how do solve this issue? Would a warning message when subscribing to a private repo be a fine solution both security and UX wise?

**Comment by jupenur** [comment]
@hanzei I'd be ok with that. The ideal solutions would be either refactoring the code to use the API token of the person *viewing* the post, or to completely disable previews for private repos, but I doubt either of those would be feasible.

An warning message should be enough as long as it's easy to notice and understand.

**Comment by hanzei** [comment]
After this this a bit more thought I'm not longer sure if a warning is the right solution here. We could warn the user on connecting the account, but that will only happen once and users might forget about it. Warning once the post is created is too late, as at this point the information as already been exposed.


Using the API token of the viewing person is not feasible as these are "plain" posts and using a custom post would drop support for mobile.

Hence I'm leaning towards disabling code preview for private completely. 1/5 Maybe with a setting? 0/5

@larkox @jupenur Let me know what you think.

**Comment by larkox** [comment]
A solution would be to reject the message if the repo is private, and send a confirmation message. Something like:
"You are sending a message with a link to a private repo, which will render the code preview. Are you sure you want to show the code preview? (Show Preview / Don't show preview / Don't send message)"

Nevertheless, I am not sure if will be a good enough UX. I guess that pasting private repos permalinks is not common enough for this being a pain point.

We can also add some settings for different use cases: disable for private repos, enable for private repos, or always ask.
In internal environments we will not be concerned of private code being showed, since it is internal.

**Comment by jupenur** [comment]
> A solution would be to reject the message if the repo is private, and send a confirmation message.

I like this idea, for one, but can't comment on the UX.

**Comment by hanzei** [comment]
While I quite like the proposed solution, it's not an easy one to implement. AFAIK it might even be impossible to also support such dialog on mobile.

I would like to fix this issue in v1.1.0, which is soon to be released. Just disabling code preview is straight forward to implement and then we can iterate with e.g. a dialog moving forward.

**Comment by larkox** [comment]
It would be possible on Mobile. You can do this with Slack Attachments with no much problem. If you want, we can discuss the way to do it.
