### ISSUE TITLE
Possible panic for nil pointer dereference

### ISSUE THREAD

**Issue by bakurits** [mattermost/mattermost-plugin-github#324]
here `rawResponse` can be nil and will produce panic 
https://github.com/mattermost/mattermost-plugin-github/blob/03935bad3a16e1c71d288b0327800e26141eb4fe/server/plugin/api.go#L790

same here for `resp`
https://github.com/mattermost/mattermost-plugin-github/blob/03935bad3a16e1c71d288b0327800e26141eb4fe/server/plugin/api.go#L1094

**Comment by hanzei** [comment]
Good catch :+1:

**Comment by EnzoBtv** [comment]
Tried to fixed it with this PR @hanzei!
