### ISSUE TITLE
Long single line code block does not wrap properly 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#330]
I have found one remaining case where the content the preview does not wrap properly and the preview pop-over becomes too wide.
![Screen Shot 2020-07-16 at 5 51 15 PM](https://user-images.githubusercontent.com/35588783/87726435-fd76ed80-c78c-11ea-80eb-769d6b501cc0.png)

This happens when there is a single line code block the is very long such as 
`{"level":"error","ts":1593397248.8786938,"caller":"mlog/sugar.go:23","msg":"ERROR: ","plugin_id":"jira","Status":"500","Error":"[object Object]: jira_instance_1441a7909c087dbbe7ce59881b9df8b9: not found","Host":"dkh-local.ngrok.io","RequestURI":"/plugins/jira/api/v2/get-search-issues?fields=key%2Csummary&q=&instance_id=%5Bobject%20Object%5D","Method":"GET","query":"fields=key%2Csummary&instance_id=%5Bobject+Object%5D&q="}`

Steps
- Deploy GitHub plugin that has all the fixes from https://github.com/mattermost/mattermost-plugin-github/pull/301 applied
- Enable and configure GitHub plugin
- Post `https://github.com/DHaussermann/hello-world/issues/40` to a channel
- Mouse over for preview

**Observed** Pop-over is too wide

**Comment by hanzei** [comment]
@asaadmahmood I tried fixing this issue, but didn't found a solution due to my lack of css knowledge. Do you have the time to take a look?

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-github/pull/339
