### ISSUE TITLE
Unable to create a subscription that watches for multiple label

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#347]
Subscriptions are working as expected when there is only 1 label. But if I try to crate a subscription with multiple labels, only the first label works. 
It may be that multiple labels was never supporter but if so, we should clarify the UI feedback to inform the user creating the subscription. 

Steps:
- Type `/github subscribe DHaussermann/hello-world issues,label:"help""bug"`   
- Note the UI says `Successfully subscribed to <repo name>` and list command shows ` issues,label:"help""bug"`
- Create and issue with label `help`
- Note webhook is fired and event is delivered 
- Create and issue with label `bug`

**Observed**: Nothing happens
**Expected** 
A. Subscription works with multiple labels 
OR
B. Plugin validates that attempting to create a subscriptions that watches multiple labels is invalid.

**Comment by DHaussermann** [comment]
@hanzei  Note that this behavior is not new to the recent release and I am unsure if this is a bug or feature request.

**Comment by hanzei** [comment]
@DHaussermann Multiple labels are indeed not supported. Given that labels can include `"` it's also quite hard to implement this feature. Hence, I will submit a PR to improve the documentations.
