### ISSUE TITLE
Command `make debug-deploy` does not work

### ISSUE THREAD

**Issue by kosgrz** [mattermost/mattermost-plugin-github#357]
This command tries to run the `debug` script that is not defined in the `webapp/package.json` file. 
The result of `make debug-deploy` is as follows:
```
make debug-deploy 
go: downloading github.com/mattermost/mattermost-server/v5 v5.23.0

// skipped many irrelevant lines

found 8 vulnerabilities (7 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
touch webapp/.npminstall
cd webapp && \
/usr/bin/npm run debug;
npm ERR! missing script: debug

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kosgrz/.npm/_logs/2020-08-28T21_55_49_213Z-debug.log
make: *** [Makefile:81: webapp-debug] Error 1

```

**Comment by larkox** [comment]
The package.json file is missing the debug script. If you want to solve it locally, you just have to add this line to the scripts on the package.json file:
`"debug": "webpack --mode=none",`

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-plugin-github/pull/345 Will fix this.
