### ISSUE TITLE
Private repositories - working?

### ISSUE THREAD

**Issue by crudolf** [mattermost/mattermost-plugin-github#36]
When I do 

/github subscribe crudolf/XYZ

where XYZ is a private repository. The plugin tells me, that the repository cannot be found "Unknown repository .."

Can this plugin only handle public repositories?

**Comment by jwilander** [comment]
It currently only works with public repositories. Some permission checking would need to be added and an update of the OAuth scopes to allow for that

**Comment by jwilander** [comment]
If someone wants to take a stab at this, that would be very welcome. I can help answer questions and point in the right direction
