### ISSUE TITLE
Cannot subscribe to private repo

### ISSUE THREAD

**Issue by prosanhive** [mattermost/mattermost-plugin-github#361]
My apology I might be stupid but I cannot get this to work:

When using

`/github subscribe mattermost/mattermost-server`

it works.

adding 
` issues,pushes,creates,deletes` results in
`Just one list of features is allowed`

but 

`/github subscribe reponame/somename issues,pushes,creates,deletes`

doesn't work at all. I read the Docs 5 time now :)

It is a private repo but I enabled Private Repos and disconnected and reconnected the account successfully.

What could the problem be?

**Comment by hanzei** [comment]
Did you connect your account using `/github connect private`? What error message are you seeing?

**Comment by prosanhive** [comment]
Yes, the account is connected. When I subscribe to mattermost/mattermost-server

 that works, but I cannot subscribe to my private repo:

```
/github subscribe reponame/somename

**Comment by hanzei** [comment]
Just to double check: Did you connect using `/github connect private` or `/github connect`?

**Comment by prosanhive** [comment]
I disconnected ``
` /github disconnect  ``` and connected again and with 
```
/github connect private
```

**Comment by prosanhive** [comment]
Nevermind. It just worked now.

I have no idea why. Sorry.
