### ISSUE TITLE
Create a webhook via a slash command in mattermost 

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-github#379]
Add a feature that will allow users to add and list webhooks in GitHub via a Mattermost slash command. The user would pass in a GitHub repository and a slash command would create a webhook on behalf of the connected Mattermost user. 

A list option would also show the existing webhooks for the repo name passed in by the user.   

Note that this functionality is already implemented for GitLab and some of this implementation may be salvageable.

**Comment by sasha27** [comment]
@aaronrothschild is someone already working on this issue? If not then I would like to work on it. Can you please point me out to respective packages I can look into and also documentations on how I can set up a testing environment, please?

**Comment by larkox** [comment]
Sure, you can take it, @sasha27 ! The implementation in Gitlab you can find it here:
https://github.com/mattermost/mattermost-plugin-gitlab/blob/dc2be260042454cd3db7cb9cc7cf35594e34eb80/server/command.go#L244
Regarding setting up the environment, please check here:
https://developers.mattermost.com/contribute/getting-started/

**Comment by hanzei** [comment]
This is implemented via the `/github setup webhook` command
