### ISSUE TITLE
Proposal - Add a system console setting to allow disabling UI components

### ISSUE THREAD

**Issue by chetanyakan** [mattermost/mattermost-plugin-github#384]
#### Summary

Similar feature to the JIRA plugin to disable the webapp components in the GitHub plugin.

- Add a plugin.json setting to allow disabling of all UI features
- This is to allow the admin to turn off the new features without affecting webhook notifications.

#### Related Links

- Related JIRA Issue and PR for the `mattermost-plugin-jira`:
https://github.com/mattermost/mattermost-plugin-jira/pull/144
https://mattermost.atlassian.net/browse/MM-16098

**Comment by hanzei** [comment]
What is the use case for this setting? Why would an admin want to prevent users from e.g. creating issues from the UI or open the custom RHS?

**Comment by larkox** [comment]
I see value on this mainly for the LHS. If more than one plugin is using the LHS to show stuff, it may get too crowded. The problem would be then how to open the RHS.

I would prefer a user-level setting, but a system level setting is easier to deal with.

**Comment by hanzei** [comment]
For todo we have a System level, right @larkox?

**Comment by larkox** [comment]
Yes, todo is working with a system level setting.

**Comment by chetanyakan** [comment]
I agree with @larkox here.

If multiple plugins are registering the teams sidebar component, then as of the current implementation, there is no scrollbar and also not possible to switch teams easily..

**Comment by hanzei** [comment]
Then let's go with a system level setting first and see if a user level one is still required.
