### ISSUE TITLE
Github connect private not working

### ISSUE THREAD

**Issue by leonheess** [mattermost/mattermost-plugin-github#388]
**Describe the bug**
If you want to connect private repositories with the Github-Mattermost-Bot you end up with
`Post "https://git.private.com/login/oauth/access_token": Forbidden`

**To Reproduce**
1. `/github disconnect`
2. `/github connect private`
3. Click on _Click here to link your GitHub account._

Is this a configuration issue?

**Comment by hanzei** [comment]
Are you running a GitHub Enterprise installation?

**Comment by leonheess** [comment]
Yes

**Comment by hanzei** [comment]
Can you confirm that you are logged into your GitHub Enterprise installation? Are there any log messages related to this issue in GitHub?

**Comment by leonheess** [comment]
@hanzei Yes, I get a login screen first, then the 2-Factor and when I successfully complete those I get the error

**Comment by leonheess** [comment]
@hanzei I just right-clicked, copied the link of _Click here to link your GitHub account._, pasted it into Chrome, and it worked... this can be closed I guess

**Comment by leonheess** [comment]
Copy-Pasted the link into the browser and it worked

**Comment by hanzei** [comment]
Glad you got it working :+1:
