### ISSUE TITLE
When using a label-filter subscription, two posts are made when an issue is created with this label

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#389]
For a subscription such as `/github subscriptions add mattermost issues,label:"Triage"`, any new issues cause a post to be made in the channel. There is a second post that occurs at the same time if the label would match `Triage`.

Now that we show the labels on the "new issue" posts, we should avoid creating the "label-added" posts during the processing of the new issue. Only the "new issue" post should be made. This probably occurs with PRs as well.

![image](https://user-images.githubusercontent.com/6913320/96181116-7bb86c80-0f01-11eb-9c2b-4cfab56f7f8b.png)

**Comment by mickmister** [comment]
If GitHub sends a separate `issue-labeled` event when the issue is created with a label, we can check if the issue was created within the last 2 seconds or something like that, in order to avoid the extra post.

**Comment by EnzoBtv** [comment]
Hey @mickmister I'm looking for issues to colaborate. Can I get this one?

**Comment by mickmister** [comment]
Thanks @EnzoBtv!!
