### ISSUE TITLE
Assignee of issue/PR should receive notifications for new comments

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#391]
Currently only the creator of a PR/issue receives a notification when a new comment is made on the issue/PR. Assignees should also receive these notifications, but they should not receive two notifications if they are also the creator of the issue/PR.

**Comment by AgentEnder** [comment]
I'll take a go at this one if thats ok?

**Comment by mickmister** [comment]
> I'll take a go at this one if thats ok?

Sure @AgentEnder! Thanks for contributing!!

**Comment by sanjaydemansol** [comment]
can I work on this?

**Comment by mickmister** [comment]
Sure thanks @sanjaydemansol!

**Comment by dipak-demansol** [comment]
@sanjaydemansol 
i Started the testing but i need more time, i will update you.

**Comment by sanjaydemansol** [comment]
Hi @mickmister , Assignee should receive Direct message from bot?

**Comment by mickmister** [comment]
> Hi @mickmister , Assignee should receive Direct message from bot?

@sanjaydemansol That's right :+1:

**Comment by dipak-demansol** [comment]
@sanjaydemansol i found 1 issue,

**Comment by dipak-demansol** [comment]
@sanjaydemansol there is a issue, pls check below steps to regenerate it.
1) i created repo in that 2nd user created issue.
2) 2nd user assign that issue to him self and to the 3rd user.
3) now repo owner as i comment on that issue then 2nd & 3rd user is not getting the notification but if i remove any 1 assignee and add comment again then single user is getting the notification.

**Comment by hanzei** [comment]
@dipak-demansol Would you please post your test observations in the PR directly? That we they are close to the code that is getting changed.

**Comment by dipak-demansol** [comment]
> @dipak-demansol Would you please post your test observations in the PR directly? That we they are close to the code that is getting changed.

@hanzei Done.
