### ISSUE TITLE
When an issue is closed with a comment, include the comment in the resulting "closed issue" post

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#397]
There is a feature "Close with Comment" in GitHub that allows the user to comment on why they are closing the issue. The GitHub plugin does not take this comment into account when creating the post.

**Comment by hanzei** [comment]
@mickmister Do you know if the webhook event for the close event contains the information, if it was triggered alongside a comment?

**Comment by mickmister** [comment]
> Do you know if the webhook event for the close event contains the information, if it was triggered alongside a comment?

https://developer.github.com/webhooks/event-payloads/#pull_request

@hanzei It looks like it isn't available. Probably not worth the hassle, but we could scan the comments to see if there was one posted very recently. What do you think? Otherwise I'll close this ticket

**Comment by hanzei** [comment]
I'm inclined to close the ticket. Scanning the posts seems not worth and a bit error prone.

**Comment by aoguo64** [comment]
Do we know if there is a similar issue open?
