### ISSUE TITLE
Display the PR/issue author in the plugin tooltip

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#401]
Currently there is no indicator of who created a PR in the link tooltips. Just below the title of the issue/PR, we could display
`Opened by (username)`, with a link to their GitHub profile.

<img width="500px" src="https://user-images.githubusercontent.com/6913320/97242155-77c1ff80-17c9-11eb-8008-cd35a0fe90ae.png"/>

**Comment by rudhrasekar** [comment]
Can you assign this to me?
TIA

**Comment by larkox** [comment]
All yours @rudhrasekar ! Thank you for contributing! :smile:
