### ISSUE TITLE
Spontaneous React Intl in console

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#403]
Occurs intermittently after closing the RHS.  Purple dev mode banner error message fires with the attached in the js.console.

![screenshot-3](https://user-images.githubusercontent.com/16541325/97925407-9ee87600-1d61-11eb-82ba-3d171ac7d8da.png)

![image-2020-10-05-10-28-13-242](https://user-images.githubusercontent.com/16541325/97925379-93954a80-1d61-11eb-8cd5-ebb4429f0edb.png)

**Comment by Kshitij-Katiyar** [comment]
Hey @hanzei @wiggin77 
I attempted to reproduce the issue but was unable to do so. I tested across multiple MM versions, including the minimum supported version for the GitHub plugin, 7.1.0, but I could still not replicate the problem. The issue may have been resolved as part of another fix.

**Comment by raghavaggarwal2308** [comment]
Closing as fixed for now
