### ISSUE TITLE
Support subscribing to issues/PRs with an assigned Project

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#409]
Along with labels, an issue/PR can contain a Project. The plugin's subscription system can support this field, to allow for creating subscriptions scoped to a given project. More info on the `/github subscriptions` command can be found here https://github.com/mattermost/mattermost-plugin-github?tab=readme-ov-file#slash-commands

In order to fetch information on projects, we can use GitHub's GraphQL API https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects

There is existing functionality in the plugin using GitHub's GraphQL API https://github.com/mattermost/mattermost-plugin-github/tree/master/server/plugin/graphql

<img width="400px" src="https://github.com/mattermost/mattermost-plugin-github/assets/6913320/a7285d19-4497-4200-9cff-cabd95b4b890"/>

**Comment by Kshitij-Katiyar** [comment]
Hi @wiggin77,
I looked into this issue and would like to share some findings with you:
When a project is added to an issue at the time of its creation, the webhook data does not contain the project-related information.
Similarly, when a project is added to an issue or pull request, a webhook is triggered, but the webhook data lacks information related to the issue or pull request.

A possible workaround to allow subscribing to issues or pull requests with an assigned project is as follows:
For issue creation, we can retrieve the project linked to the issue using the following API:
```
query {
  repository(owner: "$OWNER", name: "$REPO") {
    issue(number: $ISSUE_NUMBER) {
      projectItems(first: 10) {
        nodes {
          project {
            id
            title
          }
        }
      }
    }
  }
}
```
For the project-added webhook event, we can use a GraphQL API call to retrieve all issues or pull requests linked to the project. We can then check if any issues or pull requests have a subscription with the assigned project.
We must add the read project scope to the OAuth app request.
Update the webhook configuration to send project events.

**Comment by wiggin77** [comment]
> * The above approach will get very complex and will take some time to implement. Also, we might have to handle many edge cases.

@Kshitij-Katiyar let's wait until a customer actually requests this.  We can re-open if needed.
