### ISSUE TITLE
Allow more characters in the title field when creating a Github Issue from MM

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-github#411]
Currently it stops you from entering more than ~45 characters I think....annoying.

**Comment by haardikdharma10** [comment]
Hi @aaronrothschild, can you help me with the files that need to be edited?

**Comment by hanzei** [comment]
@haardikdharma10  I suppose line in question is https://github.com/mattermost/mattermost-plugin-github/blob/4ac1aaad9175d2ce3652a16fac23a9152fe99a36/webapp/src/components/modals/create_issue/create_issue.jsx#L192. You will need to check the effect on the GitHub API though.
