### ISSUE TITLE
Add `--exclude` option to `subscriptions` command

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-github#418]
Currently, subscriptions allow adding repositories or an organization to a subscription.

This request is to add a `--exclude` flag that will allow excluding repositories from the notification.

`/github subscriptions add mattermost,label:"Severity/Critical" --exclude mattermost/mattermost-server,mattermost/mattermost-webapp`

An example would be to subscribe a channel to all mattermost organization repositories but exclude the webapp, redux, and server repositories.

**Comment by balan2010** [comment]
Hi! I would like to work on this

**Comment by larkox** [comment]
All yours @balan2010 . Thanks!

**Comment by balan2010** [comment]
Cheers :-)

**Comment by jfrerich** [comment]
Woohoo! Thanks, @balan2010! This feature will be so helpful

**Comment by balan2010** [comment]
No Worries.. About to start  working on this issue

**Comment by hanzei** [comment]
Reopening as  https://github.com/mattermost/mattermost-plugin-github/pull/457 has been reverted

**Comment by hanzei** [comment]
@sanjaydemansol Assigning you as you are working on https://github.com/mattermost/mattermost-plugin-github/pull/505
