### ISSUE TITLE
userprofile hover github url is pointing to github.com

### ISSUE THREAD

**Issue by zetaab** [mattermost/mattermost-plugin-github#42]
When this plugin is enabled, and you check someones userprofile in mattermost. There is github information if github plugin is enabled in that user. However, that url will always point to github.com instead of correct github what is defined (in our case github enterprise url)

**Comment by sandlis** [comment]
Is it okay if I give it a try?

**Comment by enahum** [comment]
Hey @sandlis yes sure, thanks for looming at it.
