### ISSUE TITLE
Option To Disable Daily Update

### ISSUE THREAD

**Issue by frakman1** [mattermost/mattermost-plugin-github#423]
I got this plugin to work. I like having the sidebar widget and the ability to use `/github` commands. However, I am not interested in getting a daily message from the GitHub bot. Is there a way for me to disable that feature?

**Comment by hanzei** [comment]
@frakman1 You can disable the daily reminder by using `/github settings reminders off`.

**Comment by frakman1** [comment]
Awsome! I just realised that you can scroll down and see more command options than just connect, disconnect, help and todo. I guess my theme was so dark, I didn't see the scroll bar.
Thank you!

**Comment by frakman1** [comment]
Sure.  Maybe the window can be larger?


![image](https://user-images.githubusercontent.com/5826484/108858308-0305a300-75ba-11eb-8a6c-ecbb2a2655ce.png)

**Comment by hanzei** [comment]
@aaronrothschild @abhijit-singh That is some interesting feedback :point_up:

**Comment by frakman1** [comment]
I keep getting daily updates dispite entering the command to disable notifications.

FYI, the confirmation message doesn't actually say what it did. It would be more useful to show what setting was updated instead of just: "Settings Updated"

![image](https://user-images.githubusercontent.com/5826484/109720895-acc7cf80-7b78-11eb-98d2-702677531cf4.png)

That way I could prove that I disabled it, then got an update the next day with a screenshot:

![image](https://user-images.githubusercontent.com/5826484/109720974-c79a4400-7b78-11eb-939a-330014bbc86c.png)

**Comment by frakman1** [comment]
Does restarting the server reset my notification setting? Does it persist across server reboots?

**Comment by hanzei** [comment]
@frakman1 Just to double check: Did you run `/github settings reminders off`?

**Comment by frakman1** [comment]
Yes. I have two Teams in my instance. Could that make a difference? Do I have separate settings per team or are they common?

**Comment by hanzei** [comment]
The setting is global. Do you see any errors regarding the github plugin in your logs?
