### ISSUE TITLE
This plugin failed to start. Check your system logs for errors.

### ISSUE THREAD

**Issue by jidl-gh** [mattermost/mattermost-plugin-github#428]
I've gone through the prcoess of adding an OAuth client to github, entered the client ID and secret to the plugin config.

I can't seem to get the plugin to start though. I get the message: 

_This plugin failed to start. Check your system logs for errors._

As far as I can see the logs aren't availabe on the Mattermost cloud version.

The plugin version is 2.0.0. Any ideas?

**Comment by hanzei** [comment]
@jidl-gh Did you followed the steps at https://github.com/mattermost/mattermost-plugin-github#configuration before starting the plugin?

**Comment by jidl-gh** [comment]
I did. But the Step 6 failed:

_Once you have successfully registered the Mattermost GitHub Plugin as an authorized OAuth app, switch to Mattermost and run /github connect in a Mattermost channel. You should receive a DM from the GitHub plugin about the features you have available._

Which led me to investigate further and see that the plugin doesn't start.

Does the starting of the plugin depend on a connection to the OAuth app? Or should it start regardless?

**Comment by mickmister** [comment]
@hanzei Maybe we should reconsider how we handle the non-configured state of the plugin. Instead of aborting the startup, we could have the plugin in an "inactive" state while still running. We would also need to provide feedback when the credentials are updated or some way of affirming that the plugin is correctly set up. This would be a much better experience for this situation where admins that can't access the logs.

**Comment by mickmister** [comment]
@jidl-gh Do you mind sending me a DM with your workspace URL on https://community.mattermost.com at `@michael.kochell`? I will try and see what's going on with the logs.

**Comment by mickmister** [comment]
Also can you please try restarting the plugin after setting the credentials if you haven't already?

**Comment by hanzei** [comment]
> @hanzei Maybe we should reconsider how we handle the non-configured state of the plugin. Instead of aborting the startup, we could have the plugin in an "inactive" state while still running. We would also need to provide feedback when the credentials are updated or some way of affirming that the plugin is correctly set up. This would be a much better experience for this situation where admins that can't access the logs.

Great suggestion :+1: Would you be open on cutting a HW- ticket for that?

**Comment by mickmister** [comment]
HW ticket https://github.com/mattermost/mattermost-plugin-github/issues/432

**Comment by raghavaggarwal2308** [comment]
@jidl-gh Are you still facing the issue or we can close it?
