### ISSUE TITLE
Access Token Upgrade To New Format

### ISSUE THREAD

**Issue by frakman1** [mattermost/mattermost-plugin-github#431]
I got an email from Github informing me that the token used for this integration is deprecated.

Is a change to this plugin required to work properly with the new format?

> [GitHub API] Update your access token to the new format
> GitHub <noreply@github.com>
> Mon 4/5/2021 7:05 PM
> Hi @frakman1,
> 
> We noticed that, at April 5th, 2021 at 23:05 (UTC) your application (Mattermost GitHub Plugin - MM, with a user-agent header of go-github) accessed the GitHub API with a token that has an outdated format.
> 
> In order to provide additional security benefits to all our customers, we recently updated the format of our API authentication tokens. Please update your authentication tokens to take advantage of these benefits. You can reset your token with this API endpoint: https://docs.github.com/en/rest/reference/apps#reset-a-token.
> 
> To understand more about this change, and why it's important, visit https://developer.github.com/changes/2021-04-05-behind-githubs-new-authentication-token-formats.
> 
> Thanks,
> The GitHub Team

**Comment by hanzei** [comment]
Are you running the latest version of the GitHub plugin?

**Comment by frakman1** [comment]
I'm running this version:

![image](https://user-images.githubusercontent.com/5826484/113675402-5115c800-9689-11eb-9de1-78641bdc0942.png)

**Comment by hanzei** [comment]
That's surprising. Since `v31.0.0` of the `go-github` library authentication is done via HTTP headers, not query parameters. This was fixed in https://github.com/google/go-github/pull/1469. That version is also used for `v2.0.0` of this plugin. (https://github.com/mattermost/mattermost-plugin-github/blob/ed9060a93008376a2f201e8820112759ce19c7fb/go.mod#L7)

I will discuss this ticket with my team and come back to your. Thanks for the report!

**Comment by frakman1** [comment]
Sure. Let me know if there are any other components/versions you need.

**Comment by hanzei** [comment]
Just to double check: Did you recently update to `v2.0.0` of this plugin?

**Comment by frakman1** [comment]
I don't think so. I only recently installed Mattermost and all plugins within the last few months

**Comment by hanzei** [comment]
@levb Create a JIRA ticket for you: https://mattermost.atlassian.net/browse/MM-34646

**Comment by marianfeiler** [comment]
I havbe version 2.0.1 installed but get the Error:
`oauth2: server response missing access_token`
I did all the things mentioned for installing the Plugin.

**Comment by MikeN123** [comment]
Note that the JIRA ticket says this was solved - but I think it isn't. This is about the `access_token` format - you need to renew access tokens by calling the reset endpoint: https://docs.github.com/en/rest/reference/apps#reset-a-token

**Comment by hamstu** [comment]
Yeah, I also got the same email from GitHub. Is there a straightforward way to fix / resolve?

**Comment by sanjaydemansol** [comment]
Turns out, I had trailing space in my access_token. It was really bad error message though, should be fixed.

**Comment by larkox** [comment]
@sanjaydemansol Do you mind creating a ticket to improve the error message?

**Comment by mickmister** [comment]
@levb Does this issue need another look based on feedback above?

**Comment by MikeN123** [comment]
@mickmister https://mattermost.atlassian.net/browse/MM-34646 was already reopened, but it seems it's just getting pushed forward.
