### ISSUE TITLE
How can I susbcribe to a whole organisation?

### ISSUE THREAD

**Issue by cpitclaudel** [mattermost/mattermost-plugin-github#44]
Hi!

Is there a way to subscribe a channel to all repos in a Github organization? I only found `/github subscribe org/repo`, which requires one command per repository (and does not add new repositories).

Thanks!

**Comment by jwilander** [comment]
Hi @cpitclaudel, currently you need manually subscribe to each repository if you wanted to do this. I'm not opposed to adding a feature for this though. I've added the help wanted label in case someone wants to work on it

**Comment by benschuster788** [comment]
I'll take this one

**Comment by jasonblais** [comment]
If anyone is interested working on this ticket:

1. First PR merged here: https://github.com/mattermost/mattermost-plugin-github/pull/56
2. Second PR was closed, but not merged, here: https://github.com/mattermost/mattermost-plugin-github/pull/52

Moreover, a PR to unsubscribe from a PR was closed but not merged, here: https://github.com/mattermost/mattermost-plugin-github/pull/53

**Comment by hanzei** [comment]
Submitted a PR to fix 2.

**Comment by dhadiseputro** [comment]
I'll work on this, from where benschuster788 left off. I am not familiar yet with the code base and this can be my 'hello world' project if you guys allow. Am I good to take his code and add the fixes need in #53 and #56 ?

**Comment by jasonblais** [comment]
@dhadiseputro Go for it! If you have any questions working through it let us know. You're also open to sharing the approach you're planning to take for review 👍

**Comment by dhadiseputro** [comment]
I am planning to do something similar to benschuster.
The high level idea is, in `SubscribeOrg` I'll get all the repos in that org and do `AddSubscription` for each repo.

I have a question:
- If we pass `repo=""` to `Subscribe`, we will get here https://github.com/mattermost/mattermost-plugin-github/blob/master/server/subscriptions.go#L84, but then `ghOrg` is not getting use anywhere after that. Also, `repo` will still be empty, how can we continue to do the `AddSubscription` at the end of the method?

**Comment by jasonblais** [comment]
pinging @crspeller or @aaronrothschild on the above

For `channelID` - that refers to the ID of a Mattermost channel. To find the ID of a channel, click the dropdown next to the channel name, then select "View Info". The ID is displayed at the bottom of the resulting dialog

![image](https://user-images.githubusercontent.com/13119842/62048039-d91bad00-b1d9-11e9-99c9-abc22737d7a2.png)
![image](https://user-images.githubusercontent.com/13119842/62048058-e3d64200-b1d9-11e9-8883-1644a3d1a4b2.png)

**Comment by crspeller** [comment]
Looks like https://github.com/mattermost/mattermost-plugin-github/pull/67 already implements this? 
Is there work left to do on this ticket? @jwilander

**Comment by dhadiseputro** [comment]
Ah, yes.. #67 implemented this ticket. So `repo` can have the value of either just the org's name or the complete `org/repo` right? I was a little confused with the var naming

**Comment by jwilander** [comment]
Yes, sorry should have closed this earlier. Sorry for the churn @dhadiseputro
