### ISSUE TITLE
Handle event for when someone "Stars" a repository

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#444]
Currently, we don't handle the "Stars" webhook event available in the picture below. We can handle a "star" event by including it in the subscription options in the plugin. Then a user can configure the subscriptions to create a post when someone stars the repo.

![image](https://user-images.githubusercontent.com/6913320/117733718-0a534a80-b1c0-11eb-9bbe-9a59a5d780d3.png)

**Comment by niteeshhegde** [comment]
May I take up this one?

**Comment by mickmister** [comment]
Sure thing, thanks @niteeshhegde!

**Comment by sanjaydemansol** [comment]
@mickmister , I would love to work on enhancement.

**Comment by mickmister** [comment]
Hi @niteeshhegde, do you still plan on working on this feature?

**Comment by niteeshhegde** [comment]
Hi @mickmister 
I am very sorry,
I couldn't make time for this.
Please reassign it to someone
