### ISSUE TITLE
Filter out "<details>...</details>" text from PR descriptions

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#445]
Bots such as @dependabot often make posts structured with the [`<details>`](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) tag to hide details that can be expanded when clicked. When this is rendered in a Mattermost post, the result shown is the raw HTML containing the details. We can hide this text since it is mostly unnecessary information that is not properly formatted.

The `<details>` block can be replaced with the text "(details collapsed)"

![image](https://user-images.githubusercontent.com/6913320/118043137-fab03f00-b342-11eb-9236-6b9c9754131b.png)

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/c6asq8azj3gz8et78kge9hq6ea) *by `@thiefmaster`*._

**Comment by niteeshhegde** [comment]
may I take this up?

**Comment by mickmister** [comment]
Sure @niteeshhegde! Let me know if you have any questions.

**Comment by mickmister** [comment]
This HTML sanitization library may be helpful for this https://github.com/microcosm-cc/bluemonday/blob/cada0f039b5e2b75cd17eeccc7822e5fa35cfd82/policy.go#L689
