### ISSUE TITLE
Fail to enable plugin

### ISSUE THREAD

**Issue by tgly307** [mattermost/mattermost-plugin-github#45]
My mattermost server is 5.8.0, I start server with docker-compose and make plugins folder as volume by use `- ./volumes/app/mattermost/plugins:/mattermost/plugins:rw`

After I uploaded the plugin and set the config, I click the Enable button and got log below, plugin enable failed. Did I miss something?

`{"level":"error","ts":1550461595.1755967,"caller":"app/plugin.go:97","msg":"Unable to activate plugin","plugin_id":"github","error":"unable to copy webapp bundle directory: github: mkdir client/plugins/github: permission denied","errorVerbose":"mkdir client/plugins/github: permission denied\nunable to copy webapp bundle directory: github\ngithub.com/mattermost/mattermost-server/plugin.(*Environment).Activate\n\t/go/src/github.com/mattermost/mattermost-server/plugin/environment.go:189\ngithub.com/mattermost/mattermost-server/app.(*App).SyncPluginsActiveState\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:95\ngithub.com/mattermost/mattermost-server/app.(*App).InitPlugins\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:126\ngithub.com/mattermost/mattermost-server/app.(*Server).RunOldAppInitalization.func6\n\t/go/src/github.com/mattermost/mattermost-server/app/server_app_adapters.go:142\ngithub.com/mattermost/mattermost-server/app.(*Server).InvokeConfigListeners\n\t/go/src/github.com/mattermost/mattermost-server/app/config.go:169\ngithub.com/mattermost/mattermost-server/app.(*Server).UpdateConfig\n\t/go/src/github.com/mattermost/mattermost-server/app/config.go:58\ngithub.com/mattermost/mattermost-server/app.(*App).UpdateConfig\n\t/go/src/github.com/mattermost/mattermost-server/app/config.go:62\ngithub.com/mattermost/mattermost-server/app.(*App).EnablePlugin\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:245\ngithub.com/mattermost/mattermost-server/api4.enablePlugin\n\t/go/src/github.com/mattermost/mattermost-server/api4/plugin.go:187\ngithub.com/mattermost/mattermost-server/web.Handler.ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/web/handlers.go:143\ngithub.com/mattermost/mattermost-server/web.(*Handler).ServeHTTP\n\t<autogenerated>:1\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:162\ngithub.com/mattermost/mattermost-server/app.(*RateLimiter).RateLimitHandler.func1\n\t/go/src/github.com/mattermost/mattermost-server/app/ratelimit.go:107\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1964\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:78\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.(*recoveryHandler).ServeHTTP\n\t<autogenerated>:1\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2741\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1847\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"}`

**Comment by cpanato** [comment]
thanks for reporting this issue @tgly307 
you need to make the `/mattermost/client/plugins` as well

**Comment by tgly307** [comment]
@cpanato thx for reply.
I have also set `/mattermost/client/plugins` as volume with `- ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw`, but it doesn't work.
My docker-compose file is very similar with [this](https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml) expect user & password.

**Comment by tgly307** [comment]
@cpanato hi, I have found something. I forget to excute` chown -R 2000:2000 ./volumes/app/mattermost/`

I will close it.
