### ISSUE TITLE
Support notification links to GitHub discussions

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#450]
Currently when the user has an unread notification in a GitHub discussions thread, such as the posts seen here https://github.com/mattermost/community/discussions, the unread notification shows in the GitHub plugin's notification section, but the notification does not have a clickable link to navigate to the discussion.

The task here is to detect that a notification is for a GitHub discussion, and allow the user to click a link in Mattermost to navigate to the specific discussion for the notification.

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/5jp59pssitdc8nn45qbiohk6pr) *by @agarciamontoro*._

**Comment by mickmister** [comment]
Example view of the notifications

![image](https://user-images.githubusercontent.com/6913320/123459296-19495d00-d5b4-11eb-893f-21972265dc96.png)

**Comment by sanjaydemansol** [comment]
@mickmister, I would like to work on this.

**Comment by sanjaydemansol** [comment]
Our plugin uses property `html_url` from the API response as link to all notifications, but in case of _discussions_, this value is empty(`""`). Maybe we can get link to _specific discussion for the notification_ by making additional API requests to Thread endpoint, but [GitHub Discussions](https://docs.github.com/en/discussions) is in **Beta**. 4/5 we wait, the issue may resolve on its own. @mickmister your thoughts?

**Comment by mickmister** [comment]
@sanjaydemansol Thanks for looking into this. Performing a request for each notification would be very costly. 1/5 we should close this ticket for now and we have this info if someone brings this up in the future.
