### ISSUE TITLE
GitHub - Unable to fetch repos (master branch)

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#451]
When master brach of the repo is deployed I'm unable to get the list of repos in the create or attach modal. 

The drop down stays empty and and I see a 500 response in the browser dev tools.

![image](https://user-images.githubusercontent.com/35588783/123842882-42812a80-d8df-11eb-9864-c4d5398b1e3c.png)
![image](https://user-images.githubusercontent.com/35588783/123842912-4a40cf00-d8df-11eb-9405-c722fe715b73.png)

Steps:
- Build GitHub plugin from `master` branch
- Deploy and configure the plugin with oAuth configuration
- Connect a test user (who has access to at least 1 repo)
- Make a post 
- Click the ... menu and select Create GitHub issue 

**Observed**
No repos are listed and there is a 500 response.

Jira: https://mattermost.atlassian.net/browse/MM-36742

**Comment by hanzei** [comment]
This is a regression cause by https://github.com/mattermost/mattermost-plugin-github/pull/422.
