### ISSUE TITLE
Change link tooltip css to fix cutoff words in word wrap

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#455]
Currently, the PR/issue body in the plugin's link tooltip feature shows some undesirable word wrap behavior. There's no indication that a word is wrapping to the next line.

Please see https://github.com/mattermost/mattermost-plugin-github/issues/455#issuecomment-878426358 for the solution

<img width="500" src="https://user-images.githubusercontent.com/6913320/125117891-deb7e800-e0bc-11eb-9a73-58cd70fc6952.png"/>

**Comment by mickmister** [comment]
@matthewbirtch Do you have any input on how this could be improved?

**Comment by matthewbirtch** [comment]
> @matthewbirtch Do you have any input on how this could be improved?

@mickmister it looks like there are some css rules that are causing this:

In the css below, `hyphens: auto` and `word-break: break-all` is causing the undesirable behaviour. I just disabled those properties in the inspector and it seemed to fix it.

```
.github-tooltip .tooltip-info .markdown-text {
    -webkit-hyphens: auto;
    -ms-hyphens: auto;
    hyphens: auto;
    max-height: 150px;
    line-height: 1.25;
    overflow: hidden;
    word-break: break-all;
    font-size: 12px;
}
```

I'm not 100% why these rules were added to begin with though, so I can't guarantee it won't break anything else.

**Comment by mickmister** [comment]
@hanzei Circling you in discussion since you were heavily involved with this feature

The original PR for this feature has `hyphens: auto` but not the `word-break: break-all`. See the linked discussion: https://github.com/mattermost/mattermost-plugin-github/pull/258/files#r420088449 

Another PR added the `break-all` change as text was overflowing out of the popover: https://github.com/mattermost/mattermost-plugin-github/pull/339/files

![image](https://user-images.githubusercontent.com/6913320/125322368-b4a83500-e30b-11eb-9f22-9c5e8c3785b9.png)

@matthewbirtch Any ideas on this, given the background information on this feature?

**Comment by matthewbirtch** [comment]
@mickmister I think if you use the following it would be better:

```
overflow-wrap: break-word;
word-wrap: break-word;
word-break: break-word;
```

If you do the above, you shouldn't need `hyphens` either

Here's a css tricks article on this for reference: https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/

**Comment by haardikdharma10** [comment]
Thank you for your help and the article you linked to @matthewbirtch! 

@mickmister, i'll fix this 🙂
