### ISSUE TITLE
Plugin user profile image is missing

### ISSUE THREAD

**Issue by tgly307** [mattermost/mattermost-plugin-github#46]
I have connect the plugin to github, but I found the user profile image can't load correct.
![image](https://user-images.githubusercontent.com/25153311/52994912-0b1f2b00-3454-11e9-93a6-665ff3b75ffc.png)
The image link is `https://mattermost-server/api/v4/image?url=https%3A%2F%2Fassets-cdn.github.com%2Fimages%2Fmodules%2Flogos_page%2FGitHub-Mark.png`, it return 403 error.
And I found [GitHub-Mark.png](https://github.com/mattermost/mattermost-plugin-github/blob/2dbc427e6e6a8cbd3b381a769040186b9ea07ad6/server/api.go#L22) is 404, can the plugin use my own profile image?

**Comment by jwilander** [comment]
Yes, seems like the image the plugin pointed to (a github hosted image) no longer exists. The proper solution is to have include the image with the plugin and have it serve it through the REST API. I'm planning on updating the plugin shortly with the fix but if someone wants to work on it instead feel free

**Comment by hanzei** [comment]
FYI there is currently a discussion about how plugins should handle static files: https://community-daily.mattermost.com/core/pl/qm9houtcx7rgtf9akeyci5htqr

**Comment by jwilander** [comment]
I'm going to work on this now
