### ISSUE TITLE
Trailing space in my access_token causes uninformative error message

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#461]
Hi, I just Installed this plugin `oauth2: server response missing access_token`. How to resolve? do I need to renew? I've created this token just now.

-----

Turns out, I had trailing space in my access_token. It was really bad error message though, should be fixed.

_Originally posted by @sanjaydemansol in https://github.com/mattermost/mattermost-plugin-github/issues/431#issuecomment-883065815_

**Comment by sibasankar-demansol** [comment]
@mickmister  can i pick this up

**Comment by mickmister** [comment]
@sibasankar-demansol Assigned 🙂

**Comment by sibasankar-demansol** [comment]
@mickmister  I guess while storing the access_token if we trim the extra spaces it will work ? Please confirm

**Comment by mickmister** [comment]
@sibasankar-demansol Yeah that sounds good. You originally found this issue right? Maybe you can try to break the functionality some other ways and make a robust solution to defend against other potential issues.

**Comment by sibasankarnayak** [comment]
@mickmister 
Yes tried adding a extra space intentionally and reproduced the error 
Just had a look into code base 
Where we use the config API to store data
If we can make a possible change into that part

Or we can use the getConfig function to trim spaces 

Any suggestions ?

**Comment by mickmister** [comment]
@sibasankar-demansol 1/5 We should correct the input before we persist it in the database/config

**Comment by sibasankarnayak** [comment]
> @sibasankar-demansol 1/5 We should correct the input before we persist it in the database/config

@mickmister  you mean we should do it from the UI part which will remove the unwanted spaces if any ?

**Comment by mickmister** [comment]
> @mickmister you mean we should do it from the UI part which will remove the unwanted spaces if any ?

@sibasankarnayak Oh right, we don't have control over how stuff gets saved in the system console. If it doesn't seem possible to adjust the value before it's saved, then we'll need to clean up the value when we read it, which works for me :+1:

@hanzei Any thoughts on this?

**Comment by sibasankarnayak** [comment]
@mickmister  
Sure will wait for @hanzei  confirmation and then ll start working on it 

Till that will try to check if we can do it before we save

**Comment by mickmister** [comment]
@sibasankarnayak This ticket is fairly low impact so I wouldn't spend too much time on the config save strategy. Feel free to implement the other strategy if you'd like to complete ticket
