### ISSUE TITLE
Master branch no longer shows UI elements when user connects to GitHub

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#477]
I have notice that there seems to be an issue in the master branch of GitHub. When the user connects to GitHub the LHS no longer shows the list of tasks. (the slash command still works to retrieve this data)

Also the post menu options to create or attach to GitHub are no longer shown.
I can't see anything in the console or logs to show what specifically is causing this

This does not occur when installing the latest production release on an affected server.   

Steps:
- Install and configure GitHub
- Enable the plugin
- Connect to GitHub
**Observed** : User is connected but the UI has not changed.

Captured in Jira here: https://mattermost.atlassian.net/browse/MM-38232

**Comment by sanjaydemansol** [comment]
@DHaussermann I followed suggested steps, can't replicate the issue. can you please share more context details like:
- are you using it with personal or organization account ?
- does that happen with all users for that Mattermost instance?
- is Mattermost instance latest version or some specific version?
- any other details you would like to share?
