### ISSUE TITLE
Only show merged pulls

### ISSUE THREAD

**Issue by Philmod** [mattermost/mattermost-plugin-github#481]
Hi,

Is it possible to only show when the pull requests are merged? (and not when they are created, updated, etc...)

Thanks,
Philippe

**Comment by hanzei** [comment]
Not right now. What is the use case that you care about?

**Comment by Philmod** [comment]
Hey @hanzei,

We are mostly interested in changes that can affect the system, so only merged pull requests. When a problem arises, we check the last releases and the changes, by looking in a single Mattermost channel.

Right now, it's very chatty and we don't really care about created/updated pull requests.

Thanks!

**Comment by hanzei** [comment]
Thanks for the input  @Philmod  :+1:

For context: Something similar has already been implemented for issue in https://github.com/mattermost/mattermost-plugin-github/issues/390. The approach for issues should be similar. Maybe `pulls_creations` and `pulls_closing` are good same.
