### ISSUE TITLE
User gets unfriendly validation when GitHub domain is uppercase.

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#482]
When trying to create a subscription where the GitHub domain is in uppercase letters the user gets an invalid / unfriendly validation issue.  
![image](https://user-images.githubusercontent.com/35588783/134200032-f43d1ab3-7020-4753-a4c6-7c27b98b3b3d.png)

Steps:
- Install GitHub and connect a test user
- Post `/github subscriptions add https://GITHUB.COM/DHAUSSERMANN/HELLO-WORLD`
**Observed**: `Unknown organization https:`
**Expected**: Not sure this is something that must work but, the validation message should not mention `Unknown organization https:` Ideally we would support this or inform the user the URL is the issue.

**Comment by mickmister** [comment]
@DHaussermann The error `Unknown organization https:` is unrelated to the uppercase issue. The expected input here would be only `DHaussermann/hello-world`, and not the full URL. 1/5 we should support pasting the repo's full URL as you've attempted here.

Going to https://github.com/dhaussermann (no uppercase letters), GitHub takes me to the right page. Maybe the GitHub entities are case insensitive. That would require some investigation to determine.

**Comment by catalintomai** [comment]
Add @DHaussermann to detail the lack of support(?) for full Urls?

**Comment by Kshitij-Katiyar** [comment]
@DHaussermann @mickmister From the discussion above and from the https://github.com/mattermost/mattermost-plugin-github/issues/501. Should we close this issue?

**Comment by mickmister** [comment]
@Kshitij-Katiyar Yeah I think we can close. No need to support all caps URL imo, in case we are currently not supporting that
