### ISSUE TITLE
GitHub LHS icon will not show on 1st login until the browser is refreshed

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#492]
When a user fist logs into a Mattermost in a new browser they will not see the GitHub icons (connect **or** Pulls, Issues,Notifications etc..) on the LHS or team sidebar. 

Once a browser refresh occurs the icons are then visible and will remain visible if the user logs out and logs in again in the same browser. 

When logging in with fresh cache the issue is visible. 

This does **not** occur in the previous `v2.0.1` release.

Steps: 
- Install and enable the GitHub pligin
- Login to Mattermost as a user in a web client where GitHub has been used before and note the GitHub options are visible
- Login using a browser you have not used before (or incognito session)

**Observed** LHS options are not visible.      
![image](https://user-images.githubusercontent.com/35588783/136226064-09916e3a-4cd8-4aa6-b32c-4f9a78d32205.png)

**Comment by DHaussermann** [comment]
@aaronrothschild and @hanzei not sure if you have thoughts on how prevalent this may be. 3/5 I feel like if there is a simple solution we should hold up the release to solve this.

**Comment by vicky-demansol** [comment]
@aaronrothschild I tested this and I'm not sure how this could be solved as it's for a very brief moment (under 2 seconds ). Any ideas  ?

**Comment by DHaussermann** [comment]
@vicky-demansol strange, it seems like you're having issues reproducing the issue. I was not seeing this happen for only a couple seconds. The app was simply sitting in this state.

**Comment by dipak-demansol** [comment]
@DHaussermann tested as you told and with the version GitHub (github - 2.1.0) and **the issue is not Regenerated.** **pls let me know should i try something else**

**Comment by DHaussermann** [comment]
I tested this over again on my local and can see the same issue today

https://user-images.githubusercontent.com/35588783/140181436-2f4c9659-d053-40e8-a00f-cfb1068e1d5b.mov

@dipak-demansol let's sync-up offline and see what the difference is with you not being able to repro this.

**Comment by sanjaydemansol** [comment]
> I tested this over again on my local and can see the same issue today
> 
>  GitHub.Refresh.mov 
> @dipak-demansol let's sync-up offline and see what the difference is with you not being able to repro this.

@DHaussermann @dipak-demansol any findings?

**Comment by DHaussermann** [comment]
@sanjaydemansol I think @dipak-demansol may be away today. 
The only things I can think of are to ensure you're building the plugin from https://github.com/mattermost/mattermost-plugin-github/pull/490 and using a browser session with fresh cache. 
Would it help if I can reproduce this on the Demansol Sandbox server?

**Comment by sanjaydemansol** [comment]
Great, thanks @DHaussermann , will let you know if have trouble reproducing.

**Comment by dipak-demansol** [comment]
@DHaussermann let's sync-up today.

**Comment by dipak-demansol** [comment]
@sanjaydemansol Found the issue, in the private window login with your account in my "staging.tk" server and you will get the issue.
