### ISSUE TITLE
Subscriptions --exclude functionality affects all channels 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#494]
When using the exclude functionality the exclusion record that get's created `owner/repo - notification : disabled` is not channel specific. These exclusions appear in channels where no subscriptions have been created yet and no exclusion was specified. 
![image](https://user-images.githubusercontent.com/35588783/136429010-e00d8d72-f24c-466e-b612-8a966036d564.png)

This affects event delivery in channel --exclude was never used and prevents events from being delivered for some of the repositories. 
Steps: 
- Create a subscription where an owner is passed in and exclude a repo `/github subscriptions add DylanH20 --exclude DylanH20/Hello-World-1`
- Test and note that events are delivered to the channel for all repos under `DylanH20` except for `Hello-World-1` (as expected)
- Create a new channel 
- Type `/github subscribe list` notice `DylanH20/Hello-World-1 - notification : disabled` is already showing
- Type `/github subscriptions add DylanH20` to subscribe to all repos under`DylanH20`

**Observed** Exclusion of `Hello-World-1` affects newly created channel

**Comment by Kshitij-Katiyar** [comment]
@DHaussermann @mickmister I tried reproducing the error but couldn't. The steps I have followed: 
1) Created an org-level subscription excluding a repo in one channel.
2) Ran the /github subscription list in another channel but got the ``` Currently there are no subscriptions in this channel ```. 
Below are the screenshots: 
![Screenshot from 2024-04-12 12-56-49](https://github.com/mattermost/mattermost-plugin-github/assets/90389917/d3f4cae3-acd5-4522-b8b5-795f36edad73)
![Screenshot from 2024-04-12 12-57-08](https://github.com/mattermost/mattermost-plugin-github/assets/90389917/2711a08b-176d-49a9-9665-f779ef7957cf)

Can you please some additional steps in regards to this.

**Comment by AayushChaudhary0001** [comment]
@DHaussermann I tried to reproduce the issue by executing the steps provided, but I am not able to do so. The message received shows as follows:
![image](https://github.com/mattermost/mattermost-plugin-github/assets/116162036/c3ce091a-6671-4682-995f-fac759cc696c)

cc: @Kshitij-Katiyar

**Comment by Kshitij-Katiyar** [comment]
@mickmister I think we can close this issue as it is not reproducible.

**Comment by mickmister** [comment]
Yeah I think this was explicitly fixed in a PR a while ago
