### ISSUE TITLE
Add support for subscriptions filtering on a GitHub "project"

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#496]
Currently you can filter on an issue or PR's labels with this plugin's subscriptions. The task here is to also support filtering on a project:

<img width="400px" src="https://user-images.githubusercontent.com/6913320/136620769-42e20778-f7fd-4c35-bdc1-5fcd02249b31.png"/>

**Comment by rinkimekari** [comment]
Currently, this is impossible using the current Rest API code, which https://github.com/mattermost/mattermost-plugin-github/pull/404 solves. Waiting for that to be merged is necessary before working on this ticket.
