### ISSUE TITLE
Validation Message spacing (UI) issue 

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-github#497]
![validaiton msg spacing issue 1](https://user-images.githubusercontent.com/89907719/136648480-b1be7b60-10ab-4649-8caa-35a5e75f6fb5.png)
![validaiton msg spacing issue 2](https://user-images.githubusercontent.com/89907719/136648484-49f4d6ee-1dea-4bfa-b78b-c8fc59754aa9.png)

1) :- between the 2nd input box and validation message has extra spacing compare to the 1st input & validation, all the validation message should have the same spacing between the input box and validation message so the UI will look better. 

2) after fixing the 1st point pls make Sure that you maintain the same space between the validation msg & "Description for the git" label, same as this.

**Comment by cyrusjc** [comment]
Hi, I would like to pick this issue up
