### ISSUE TITLE
Validation Message Should be User Friendly

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-github#498]
![validation is not user friendly](https://user-images.githubusercontent.com/89907719/136652469-8a3a02b2-9d18-409e-a34b-732f5ce9e1ac.png)

**Comment by hanzei** [comment]
This might need server side changes

**Comment by dipak-demansol** [comment]
@sibasankarnayak @adithyaakrishna @hanzei may be simple solution will be to trim the space so we don't have to worry about handling the validation

**Comment by adithyaakrishna** [comment]
@dipak-demansol I am not sure if that would be the right approach as its something to deal with validation and IMO it should give proper messages always 😶

**Comment by cyrusjc** [comment]
Hi I would like to pick up this issue.

**Comment by hanzei** [comment]
Thanks @cyrusjc :+1:
