### ISSUE TITLE
There should be a auto suggestion for a exclude Command 

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-github#507]
There should be a auto suggestion for a exclude Command because without auto suggestion The user will never know that there is a functionality like exclude.

related to #505

![There should be a auto suggetion for a exclude Command](https://user-images.githubusercontent.com/89907719/139658865-18d718b8-be9d-4192-bc22-ee9fd372e6b8.jpg)

**Comment by hanzei** [comment]
Good catch @dipak-demansol  :+1: Made this a HW.

**Comment by dipak-demansol** [comment]
@hanzei Whats your thought on this

Need to improve User experience
     1) After using /github help,The user will get the description of all command so in that need text improvement so user easily understand how to use this command, why need this? **because before exclude need to add only ORG or Owner name and then need to use the --exclude and then need to add the Owner/repo name then only this will work** so its best you add this line in the help description so user easily understand how to use this, **/github subscriptions add owner --exclude owner[/repo]**  
      
      
     
     2) in the auto suggestion we can add option like this (this will be more easy to understand)
          **menu title                      --exclude [owner/repo]
          menu description            ex :- /github subscriptions add owner --exclude owner[/repo]**
                                                                      **or** 
                  **in the future list you can add like --exclude owner[/repo]**

**Comment by dipak-demansol** [comment]
@sanjaydemansol about the point 2, need to do the 1st or 2nd thing to improve the user-experience.

**Comment by hanzei** [comment]
1) Unfortunately, the autocomplete is static. Hence, there is no way to make the flags depend of if the user did input an org or a repo. The description has to make it clear how to use the flag.

**Comment by dipak-demansol** [comment]
> 1. Unfortunately, the autocomplete is static. Hence, there is no way to make the flags depend of if the user did input an org or a repo. The description has to make it clear how to use the flag.

so we ignore the point 2 and do the text changes as per the point 1, right?

**Comment by hanzei** [comment]
I'm not sure I'm getting your suggestion in 2). There should still be an autocomplete flag for `exclude`.

**Comment by dipak-demansol** [comment]
> (2.1)

about the 2.1, we can add Command like this for exclude

![33](https://user-images.githubusercontent.com/89907719/145559002-1b588ad0-6ae9-40f4-b140-8137b1b6be21.png)

                                               **OR** 

About 2.2, We can add this text **--exclude owner[/repo]** here, pls see the image.
![55](https://user-images.githubusercontent.com/89907719/145559293-277b4da4-173c-4857-92bc-cfb64ef9e56e.png)

**Comment by hanzei** [comment]
Got it, thanks for the screenshot @dipak-demansol :+1: 

2.1. What would you add in 2.1? What information is missing in `/connect`?

2.2. The `--exclude` flag should not be part of the features list, but instead it's own autocomplete item.

**Comment by dipak-demansol** [comment]
> --exclude [owner/repo]

i suggestion was we can add this command **"--exclude [owner/repo]"**, **same as /connect.**

**Comment by hanzei** [comment]
What do you mean with "same as /connect."?

**Comment by dipak-demansol** [comment]
> What do you mean with "same as /connect."?

when i type "/github subscribe add dipak-demansol" then i add space then i should get the exclude command in the auto suggestion.

**Comment by dipak-demansol** [comment]
> What do you mean with "same as /connect."?

we can connect on call for 5 minutes, on call i can explain exactly what i'm talking about.
