### ISSUE TITLE
after Exclude the Repo, if user Subscribe the same Repo then notification is not working for that Repo.

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-github#508]
Steps :- 1) by using this command the user will subscribe all the dipak organisation Repo except sample1 Repo. /github 
                  subscriptions add dipak-demansol issues,pulls,issue_comments --exclude dipak-demansol/sample1 
              2) now subscribe the Repo that we exclude, run directly this command, /github subscribe add dipak- 
                 demansol/sample1
              3) now run /github subscribe list and you can see the result same as the attached image.

issue :- because we exclude the dipak-demansol/sample1 then successfully Subscribe the same Repo still the user will not receive the notification if someone add any comments on issue, it will only work when user delete subscription of that exclude repo and then subscribe the same repo.

solution :- when user Subscribe the exclude Repo then User should get validation message  to delete that exclude Subscription Of that Repo or automatically that  exclude Subscription should deleted when user subscribe the exclude repo. 

related to #505

![IMG_20211101_164939](https://user-images.githubusercontent.com/89907719/139664365-d58f4386-201d-4ee2-9cc4-8ee0cffe026b.jpg)

**Comment by catalintomai** [comment]
@mickmister - please add comments wrt to the right scoping.

**Comment by mickmister** [comment]
It seems to me that the `--exclude` flag should only affect the subscription it is applied to. If I exclude a repo in one subscription, and include the repo in another subscription in the same channel, I would expect the second subscription to receive the notifications.

I propose we change the functionality to make sure each subscription will operate on its own (not affected by `--exclude` flags in the other subscriptions), and we can make the behavior of checking for accidents setting up the subscriptions in a later release.

**Comment by catalintomai** [comment]
@sanjaydemansol - is there anyone from your team handling this? - it is supposed to be part of the next release to be completed this month.

**Comment by DHaussermann** [comment]
This issue can now be closed. The issue description is now stale and current behavior details are captured in https://github.com/mattermost/mattermost-plugin-github/issues/526 instead 

**Note** that we are still waiting on https://github.com/mattermost/mattermost-plugin-github/pull/505 to merge which will resolve both https://github.com/mattermost/mattermost-plugin-github/issues/494 and https://github.com/mattermost/mattermost-plugin-github/issues/526

cc @catalintomai
