### ISSUE TITLE
getting error when i use "/Github subscribe list" Command

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-github#510]
will add more info later

https://user-images.githubusercontent.com/89907719/140910210-5ecb2526-6ade-4209-bf59-7fddd30a04b5.mp4

**Comment by dipak-demansol** [comment]
![Screenshot from 2021-11-09 16-39-33](https://user-images.githubusercontent.com/89907719/140913815-ef3c4975-a2c0-45e1-b409-fb302d0bb20d.png)

**Comment by maisnamrajusingh** [comment]
@dipak-demansol  just wanted to confirm if the repository path that you entered in the url is a valid one.

**Comment by dipak-demansol** [comment]
> @dipak-demansol just wanted to confirm if the repository path that you entered in the url is a valid one. lets get on a call tomorrow to discuss this as this could be because of invalid repository paths.

i think the issue is generated because i exclude the Test1 repo of xyz organisation and then i subscribe the same repo. i think its because of #508 issue.

**Comment by Kshitij-Katiyar** [comment]
@dipak-demansol I tried reproducing the error but couldn't. Steps I have done:- 
1) Created an org-level subscription excluding a particular repo. 
2) Created a repo subscription with the excluded repo. 

But the list command is working fine in my case:
![Screenshot from 2024-04-12 12-29-38](https://github.com/mattermost/mattermost-plugin-github/assets/90389917/8f0cf3c3-c9a3-4315-bad6-50701d570e8c)

Is there anything else you can tell me about this error and some way to reproduce it? It would be very helpful.

**Comment by AayushChaudhary0001** [comment]
@Kshitij-Katiyar I have tried to reproduce the above issue but I am also not able to do so.

**Comment by Kshitij-Katiyar** [comment]
@mickmister I think we can close this issue as it is not reproducible.
