### ISSUE TITLE
After Subscribing event ex "pulls", existing event is removed so also need to print those removed event at the time of displaying the Success message.

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-github#512]
issue :- when i subscribe the "pulls" event for the "repo1", repo1 existing all the event is removed automatically and use is not aware of that.  

solution :- after subscribing the "pulls" event, the user will get the message as **"Successfully subscribed to sample1."** we also need to  show, because of pulls subscription which existing subscription is removed, we can display it below the success message.

**if you fix this then also pls fix this one #513**

**Comment by sibasankarnayak** [comment]
@catalintomai @hanzei 

was investing the issue do we want some message like the subscription is over written and message showing previous events and the current events ?

**Comment by hanzei** [comment]
@sibasankarnayak Sounds good to me :+1:

**Comment by sibasankarnayak** [comment]
> @sibasankarnayak Sounds good to me 👍

will it be okey if i complete this with one PR for this issue
https://github.com/mattermost/mattermost-plugin-github/issues/513

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-plugin-github/pull/517 can be used as a starting point
