### ISSUE TITLE
After subscribing the event, need to display event name with the success message.

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-github#513]
why its required :- after subscribing some event user is getting this message as "Successfully subscribed to test3."  but with the success message we can also Print the events that user just subscribed,  if we Print that then after subscription user will know that what he just subscribed and don't need to use another command to see that what just he subscribed.

**if you fix this then also pls fix this one #512**

**Comment by catalintomai** [comment]
Have a user message being posted to the channel the user is in.

**Comment by dipak-demansol** [comment]
NO, that success message is only visible for that user and for the same channel, in other channel that message will not visible.

**Comment by dipak-demansol** [comment]
Currently when i subscribe some channel by using this command as **/github subscriptions add dipak-demansol/sample1 issues,pulls** then i'm getting this system generated message as **Successfully subscribed to sample1.** but message should be like this **Successfully subscribed to sample1 : issues, pulls**

**Comment by sibasankarnayak** [comment]
@dipak-demansol are you looking for this feature

![image](https://user-images.githubusercontent.com/86650698/143868658-49ec8127-1e23-4bec-acbf-8311ed1dd626.png)

**Comment by dipak-demansol** [comment]
> @dipak-demansol are you looking for this feature
> 
> ![image](https://user-images.githubusercontent.com/86650698/143868658-49ec8127-1e23-4bec-acbf-8311ed1dd626.png)

Yes sir.

**Comment by hanzei** [comment]
The point that @catalintomai wanted to made, is that as part of this ticket not only should the events be named in the message, but I should also get posted in the channel and not as an ephemeral post.

**Comment by sibasankarnayak** [comment]
@hanzei just to be on same page ,

when you user subscribe to a repo , he should get a message  what does it actually mean

i see there is a message but a ephemeral post can you explain it bit, will be okey to connect offline or on sync up call

**Comment by hanzei** [comment]
When a user adds a subscription, there should be a bot message in the channel stating for which repo/org the subscription was created and to which events it subscribes.

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-plugin-github/pull/517 can be used as a staring point
