### ISSUE TITLE
GitHub enable disable data showing wrong

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-github#516]
issue :- when user uninstall existing GitHub plugin and install same plugin from market then by click on the config user can see that its enable but in real time its disable. its showing wrong setting.

1) remove the GitHub plugin.
2) from the market, install the GitHub plugin. (sometime i have to click 2 times on install button from the market)
3) click on the Config and user will redirect in the GitHub plugin settings.
4) there user will see the plugin is already enable = true.
5) from the side menu search plugin management and go in that menu
6) from the plugin management list you can see that GitHub plugin is disabled.

https://user-images.githubusercontent.com/89907719/143451130-b841080c-5e71-4623-94fb-414cd8edb9c3.mp4

.

**Comment by hanzei** [comment]
Moving this issue to JIRA as it's not GitHub specific: https://mattermost.atlassian.net/browse/MM-40378

**Comment by hanzei** [comment]
Good catch @dipak-demansol :+1:
