### ISSUE TITLE
Github Plugin Crash in the mattermost version 6.1.0 but the same plugin worked on mattermost ver 6.0.0 and 6.3.0

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-github#518]
**OS**          :-  Ubuntu 20.04.3 LTS
**NODE Version** :- v16.0.0
**NPM Version**   :- v7.10.0

**➜  ~ go env**           
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/qa2/.cache/go-build"
GOENV="/home/qa2/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/qa2/qa2/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/qa2/qa2/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/qa2/Downloads/go1.16.11.linux-amd64/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/qa2/Downloads/go1.16.11.linux-amd64/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.11"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build760952946=/tmp/go-build -gno-record-gcc-switches"

----------------------------
**Server Log**
----------------------------
{"timestamp":"2021-12-06 13:40:23.131 Z","level":"error","msg":"Unable to restart plugin on upgrade.","caller":"web/context.go:105","path":"/api/v4/plugins","request_id":"mdccqxtrd3ny5fnqthaw1e7e8a","ip_addr":"100.112.221.0","user_id":"cys73wxou7ffi8s1srmyohwafe","method":"POST","err_where":"installExtractedPlugin","http_code":500,"err_details":"unable to start plugin: github: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."}
{"timestamp":"2021-12-06 13:40:23.131 Z","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:109","method":"POST","url":"/api/v4/plugins","request_id":"mdccqxtrd3ny5fnqthaw1e7e8a","host":"demansol-sandbox.test.mattermost.cloud","scheme":"http","status_code":"500"}

**Github Plugin zip File Link** :- https://drive.google.com/file/d/1RWvGKGmNcHbWwB6criI25ip0TjgoM9HE/view?usp=sharing

**Comment by catalintomai** [comment]
@dipak-demansol - can you try repro-ing this with one of the other Demansol developers (do they have Ubuntu 16 or 18 that we recommend as the standard dev. platform)?

**Comment by dipak-demansol** [comment]
> @dipak-demansol - can you try repro-ing this with one of the other Demansol developers (do they have Ubuntu 16 or 18 that we recommend as the standard dev. platform)?

We already experimented with the ubantu 18 and some how build Fail to Compile but if you say then i can try again with the same Configuration on ubantu 18 and try to regenerate it.

**Comment by dipak-demansol** [comment]
but i think its not related to the OS version, because the same plugin zip is working in the mattermost 6.0.0 and 6.3.0 version

**Comment by catalintomai** [comment]
There is a workaround for now.
