### ISSUE TITLE
--exclude functionality is missing validation that prevents user creating subscriptions that contradict each other

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#526]
Currently it seems that users would be able to subscribe to a repo but then also subscribe to the organization with an `--exclude` to the same repo. This configuration should be invalid and we should prevent saving this data. 

Case 1: When adding a subscription for owner/repo check if an `--exclude` exists already for a matching owner/repo
Case 2: When adding a subscription for owner or org with an `--exclude` for a owner/repo check if an existing subscription exists for the owner/repo already

**Comment by sanjaydemansol** [comment]
this issue is fixed in this branch https://github.com/demansoltech/mattermost-plugin-github/tree/mm-494

**Comment by Kshitij-Katiyar** [comment]
@DHaussermann @sanjaydemansol Is there anything left on this issue to do or we can close this.
