### ISSUE TITLE
JS error when re/dis-connecting 

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#530]
There is a JS error I'm seeing. I have no concrete repro steps. Possibly occurs on connect/disconnect. 
`utils.js`
![image](https://user-images.githubusercontent.com/35588783/152854057-792bbfc5-81f9-4b68-a3b7-4c9c81e73cdc.png)
![image](https://user-images.githubusercontent.com/35588783/152854083-14d4952a-6f76-4cf9-bee1-30cf1aa1ac4f.png)

**Comment by hanzei** [comment]
Might be caused by https://github.com/mattermost/mattermost-plugin-github/pull/515

**Comment by hanzei** [comment]
`git bisect` tracks it down to https://github.com/mattermost/mattermost-plugin-github/pull/515

**Comment by hanzei** [comment]
cc @DHaussermann

**Comment by catalintomai** [comment]
@sanjaydemansol - any progress on this one? This is blocking the release. Thanks.

**Comment by sanjaydemansol** [comment]
@catalintomai Could not trace the bug.

**Comment by catalintomai** [comment]
cc @lufty-demansol

**Comment by maisnamrajusingh** [comment]
> cc @lufty-demansol
Im looking into this one now @catalintomai .

**Comment by maisnamraju** [comment]
I had to revert the PR for now.

**Comment by catalintomai** [comment]
> I had to revert the PR for now.

Would be helpful to include the link to the PR that was reverted. As a follow-up, what is the plan for the functionality that was reverted?

**Comment by hanzei** [comment]
@hanzei Taking a look myself

**Comment by hanzei** [comment]
Taking a look myself
