### ISSUE TITLE
Remove `password` attribute from oath field to prevent invalid filed pre-population

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#535]
I'm still seeing cases where the plugin dialogue modal for GitHub configuration is opening with login credentials already sitting in the field. 
![image](https://user-images.githubusercontent.com/35588783/154369005-c6d73476-dbc1-436f-860f-f5994936f1e8.png)

Does not repro 100% of the time but I can't pin down exact steps. 

We should consider just dropping the `password` attribute from the field to side-step this issue.

**Comment by DHaussermann** [comment]
@levb sorry for the delay in creating this issue. As per our discussion - I think one of you can quickly make a change to side-step this problem.

**Comment by hanzei** [comment]
@DHaussermann Are only `password` fields auto filed or also `text`  ones?

**Comment by DHaussermann** [comment]
@hanzei I can test this now - it's intermittent but, to answer your question - No the `Client ID` field was also affected.

**Comment by DHaussermann** [comment]
@hanzei I have tried this on 3 unique servers now. Both with existing and fresh browser cache. 
For all 6 attempts - This issue did **not** reproduce. 

It would seem the proposed solution does side step the issue. 
cc @mickmister
