### ISSUE TITLE
Change to Display Notification Counters in Left Sidebar requires a webapp refresh.

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#536]
The setting for `Display Notification Counters in Left Sidebar` requires that all connected users refresh the web app before seeing the items in the side bar appear or disappear. 

![image](https://user-images.githubusercontent.com/35588783/154372227-43d275cf-65bd-437c-89a2-255c9ff5a33f.png)
![image](https://user-images.githubusercontent.com/35588783/154372640-5f968bbe-d264-4278-856b-491a957d90fd.png)

If there is a simple solution, this may be worth resolving.

**Comment by hanzei** [comment]
Implementation: Push config changes to the client via websocket event
