### ISSUE TITLE
Attach modal shows a json error when no issues are available to attach

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#537]
When no issues are available to attach we should see s friendly message rather than a json error. This would be most common the plugin is locked to an org or repo and issue creation has been disabled there. 

![image](https://user-images.githubusercontent.com/35588783/154373610-60e734a5-9bcd-4c1a-ba60-bdb0566276f2.png)

Steps:

- Connect a test user
- Save some other value in the Organization lock such as token-org (or find an org or repo that has issue creation disabled and point there)
- Make or locate a post
- Select the ... menu and Attach to GitHub

**Observed**: The modal shown an invalid json error

**Comment by Kshitij-Katiyar** [comment]
Hey @DHaussermann @wiggin77 ,
I attempted to reproduce the issue but was unable to do so. I tested various configurations of organizations and repositories with issue creation disabled but still could not replicate the problem. It's possible that the issue was resolved as part of another fix.

**Comment by raghavaggarwal2308** [comment]
Closing as fixed for now
