### ISSUE TITLE
Mute functioanlity also silences DM from muted user

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#543]
There is functionality in GutHub to send a DM when a another GitHub user comments on PR or issues you are assigned to even if they do not have @mentions. There is also a mute feature to silence the messages from a specific user(s).

In previous releases - When a user is muted, comments on your PRs and Issues do not trigger a DM. However, if the comment contains an @mention you would get a DM regardless. 

It was recently discovered that in `master` branch and Release bump 2.1, These DMs are also muted. 

Steps:
1. Connect test user to GitHub
2. Create and issue in GitHub and assign it to yourself
3. As an alternate GitHub user, comment on the issue with **no @mention**
4. Note the test user receives the  a DM
5. As the test user in Mattermost use the GitHub mute command to mute the user in from step 3.
6. As the alternate GitHub user, comment on the issue on the issue with **no @mention**
7. Note the test user no longer receives the DM from muted user (this step is just to confirm the correct user is targeted and mute is working)
8. As the alternate GitHub user, comment on the issue on the issue with an @mention

**Observed**: No Dm is received by the test user
**Expected**: @mentions should supersede mute logic and user should receive a DM

**Comment by mickmister** [comment]
@DHaussermann I think this issue needs to have some UX discussion, as this point is a bit subjective:

> **Expected**: @mentions should supersede mute logic and user should receive a DM 

I'm not sure if the feature had this in its original design

**Comment by hanzei** [comment]
@-mentions should _should_ supersede a mute setting. If there are case where a @-mention notification gets through, that would be a bug.

@DHaussermann Could you please check if that case exists?

**Comment by raghavaggarwal2308** [comment]
Closing as the functionality is working as expected https://github.com/mattermost/mattermost-plugin-github/issues/386#issuecomment-2256029040
