### ISSUE TITLE
Mattermost system admin must reconnect their account after upgrading.     

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#544]
When GitHub is upgraded for `v2.0.1` to `v2.1.0`  sysadmin will need to reconnect their accounts. 

As shown by this screen, users who are not admins seem unaffected. 
![image](https://user-images.githubusercontent.com/35588783/155808244-e627abbb-8f89-4084-b3d2-b9a13693b8eb.png)

Not necessarily an issue but, the owner of the GitHub oAuth app will get an email about change in scope which seems directly related to this issue. 
![image](https://user-images.githubusercontent.com/35588783/155808150-de69bab8-483c-461d-b5b4-b979d73d871b.png)

Steps:
- Install GitHub 2.0.1 from the marketplace
- Configure the plugin and connect a connect a system admin
- Upgrade to GitHub 2.1.0
- Run `/ghithub me`

**Observed**: GitHub profile is no longer connected.

**Comment by hanzei** [comment]
@DHaussermann I can't reproduce this issue. If you `/github connect` again after the update?

**Comment by DHaussermann** [comment]
```
{"timestamp":"2022-02-25 17:45:38.463 Z","level":"warn","msg":"ignored duplicate step name","caller":"app/plugin_api.go:934","plugin_id":"github","name":"oauth-info","flow":"oauth"}
{"timestamp":"2022-02-25 17:45:44.154 Z","level":"warn","msg":"Failed to search for PRs","caller":"app/plugin_api.go:934","plugin_id":"github","error":"GET https://api.github.com/search/issues?q=is%3Apr+is%3Aopen+author%3ADHaussermann+archived%3Afalse+: 401 Bad credentials []","query":"is:pr is:open author:DHaussermann archived:false ","userid":"3gngahnsffnq5kuro9zcuect4h","github username":"DHaussermann"}
{"timestamp":"2022-02-25 17:45:44.193 Z","level":"warn","msg":"Failed to search for assignments","caller":"app/plugin_api.go:934","plugin_id":"github","error":"GET https://api.github.com/search/issues?q=is%3Aopen+assignee%3ADHaussermann+archived%3Afalse+: 401 Bad credentials []","query":"is:open assignee:DHaussermann archived:false ","userid":"3gngahnsffnq5kuro9zcuect4h","github username":"DHaussermann"}
{"timestamp":"2022-02-25 17:45:45.075 Z","level":"warn","msg":"Failed to search for review","caller":"app/plugin_api.go:934","plugin_id":"github","error":"GET https://api.github.com/search/issues?q=is%3Apr+is%3Aopen+review-requested%3ADHaussermann+archived%3Afalse+: 401 Bad credentials []","query":"is:pr is:open review-requested:DHaussermann archived:false ","userid":"3gngahnsffnq5kuro9zcuect4h","github username":"DHaussermann"}
{"timestamp":"2022-02-25 17:45:51.722 Z","level":"warn","msg":"Failed to list notifications","caller":"app/plugin_api.go:934","plugin_id":"github","userid":"3gngahnsffnq5kuro9zcuect4h","github username":"DHaussermann","error":"GET https://api.github.com/notifications: 401 Bad credentials []"}
{"timestamp":"2022-02-25 17:45:51.725 Z","level":"warn","msg":"Failed to search for PRs","caller":"app/plugin_api.go:934","plugin_id":"github","userid":"3gngahnsffnq5kuro9zcuect4h","github username":"DHaussermann","error":"GET https://api.github.com/search/issues?q=is%3Apr+is%3Aopen+author%3ADHaussermann+archived%3Afalse+: 401 Bad credentials []","query":"is:pr is:open author:DHaussermann archived:false "}
{"timestamp":"2022-02-25 17:46:00.224 Z","level":"warn","msg":"Failed to list notifications","caller":"app/plugin_api.go:934","plugin_id":"github","github username":"DHaussermann","error":"GET https://api.github.com/notifications: 401 Bad credentials []","userid":"3gngahnsffnq5kuro9zcuect4h"}
{"timestamp":"2022-02-25 17:46:00.254 Z","level":"warn","msg":"Failed to search for PRs","caller":"app/plugin_api.go:934","plugin_id":"github","query":"is:pr is:open author:DHaussermann archived:false ","userid":"3gngahnsffnq5kuro9zcuect4h","github username":"DHaussermann","error":"GET https://api.github.com/search/issues?q=is%3Apr+is%3Aopen+author%3ADHaussermann+archived%3Afalse+: 401 Bad credentials []"}
{"timestamp":"2022-02-25 17:46:00.260 Z","level":"warn","msg":"Failed to search for assignments","caller":"app/plugin_api.go:934","plugin_id":"github","query":"is:open assignee:DHaussermann archived:false ","userid":"3gngahnsffnq5kuro9zcuect4h","github username":"DHaussermann","error":"GET https://api.github.com/search/issues?q=is%3Aopen+assignee%3ADHaussermann+archived%3Afalse+: 401 Bad credentials []"}
```

**Comment by hanzei** [comment]
@DHaussermann I still can reproduce the issue. The old theoretical case would be:
1. Run the GitHub plugin 2.0.1.
2. Empty the configuration field `encryptionkey` i.e. set it to `""`
3. Upgrade to GitHub 2.1.0
4. Confirm that the configuration field `encryptionkey` is not longer empty.

But that case is about an admin tinkering with the config file, which should not happen.

**Comment by DHaussermann** [comment]
@hanzei Even though I saw this occur twice before filling this issue, I wonder if  this ☝️  or something else was occurring. 

I have tested the steps as described and I am also unable to reproduce the issue on the happy-path upgrade. It's possible a config change was occurring after the admin user had mapped their account. 

I have no other ideas to investigate and and the upgrade as it should occur is functional and preserving authentication of all users. We should close this issue and proceed with the release.

**Comment by DHaussermann** [comment]
I just saw this behavior again when testing the upgrade path for the marketplace release - https://github.com/mattermost/mattermost-marketplace/pull/254 

![image](https://user-images.githubusercontent.com/35588783/157550084-1db1d998-ad39-46a0-a1e3-05ded9b2ffb9.png)

Steps:
- Spin up a new /cloud server (HA if relevant)
- Install the GitHub plugin from the marketplace
- Create an oAuth app in GitHub and configure the plugin to use it
- Enable the plugin
- Created a webhook to ensure subscription also work (This may well be optional and have no affect)
- Connect 2 MM users (one admin one member) 
- Switch to local marketplace running `v2.1.0` (ngrok tunnel in place to expose this externally)
- Upgraded to `v2.1.0` from the marketplace 
- Run `github me`
**Observed** One of the target users is no longer mapped.

**Comment by DHaussermann** [comment]
@hanzei I have this issue again while testing the marketplace upgrade process for the new release. 

Please advise if you can think of any reason this would be intermittent. 

cc @catalintomai note we should decide if action is needed on this before we push the new release to the marketplace. 
We may need a way to get more data points. Thoughts?

**Comment by DHaussermann** [comment]
If it helps - Affected server is https://dkh-master-ha-11.test.mattermost.cloud

**Comment by hanzei** [comment]
@DHaussermann just to double check: After the update only one of the two users looses the GitHub connection, right? The other one's stays intact?

**Comment by DHaussermann** [comment]
> @DHaussermann just to double check: After the update only one of the two users looses the GitHub connection, right? The other one's stays intact?

Correct @hanzei . There was a 2nd user in a different browser session. This 2nd user did not seem affected.

**Comment by hanzei** [comment]
Wild guess: Could the issue be caused by users never actually using the granted oauth token? I.e. if ones run `/github me` with both users, does the issue still repo?

**Comment by hanzei** [comment]
@levb will take a look as this might be caused by https://github.com/mattermost/mattermost-plugin-github/pull/472

**Comment by levb** [comment]
@DHaussermann @hanzei After struggling with this for the better part of the day, I am unable to reproduce this consistently. I have seen the PATCH token requests to fail with a 404, but then was unable to reproduce again, after nuking the database. I wonder if the at-rest encryption key got reset in the original case, but then the token should've failed decoding?...

If either of you can reproduce consistently, please advise.

**Comment by levb** [comment]
@hanzei Let me fix this, although also need to account for HA.

**Comment by hanzei** [comment]
Maybe https://pkg.go.dev/github.com/mattermost/mattermost-plugin-api@v0.0.26/cluster#Mutex can help here
