### ISSUE TITLE
If a user edits a comment with a mention of you, you get a second notification

### ISSUE THREAD

**Issue by jwilander** [mattermost/mattermost-plugin-github#55]
Repro steps:
1. Mention a user, who has their Mattermost account connected with the plugin, in a GitHub issue/PR comment
2. Edit that comment (making sure to leave the mention in)

Observed:
Two notifications are sent to the user about the comment
<img width="1070" alt="screen shot 2019-03-01 at 15 37 03" src="https://user-images.githubusercontent.com/2672098/53665004-382fc280-3c38-11e9-96f9-e907f659eb29.png">

Expected:
Only one notification is sent

**Comment by checkaayush** [comment]
@jwilander Possible approaches on edit/delete of issue/PR comment:

1. We can skip sending the second post message completely.  
2. We can remove the @ from the mention so as to prevent the notification. 

Personally, I feel the call to action on seeing a mention is clicking on the link and going to GH to read the thing in its entirety. Any edits/deletes are evident there. Hence I favour the first one. 
 
If you have a better approach, let me know.

**Comment by hanzei** [comment]
We could update the first post with the new content. Then users could immediately see the up to date comment.

**Comment by jwilander** [comment]
I would say 1) is good enough. I like your idea @hanzei but then we'd need to track the posts and that's a lot more complexity for not a huge benefit and I agree with @checkaayush that the notification is just a CTA and meant to direct you to GH to see the full message/context

**Comment by hanzei** [comment]
Fine by me
