### ISSUE TITLE
Webhooks: Can users abuse the webhook secret if shared?

### ISSUE THREAD

**Issue by christianhueserhzdr** [mattermost/mattermost-plugin-github#550]
Dear contributors and users,

I am about to activate this GitHub plugin for Mattermost in our Mattermost instance. I would like to enable users to subscribe to their repositories on GitHub. As described in the documentation they need to create a webhook for their repository on GitHub. A webhook secret is then used to create a webhook which the Mattermost system admins provide. I would like to ask you whether users can abuse the webhook secret if I would share it? It's obviously a secret, but how are users able to get notifications without a webhook and a webhook secret? Maybe I did not understand the use case behind the subscriptions. Could you please share with me how this is supposed to work? Thank you very much for your help and advice. Maybe this could also be explained in the documentation in case others are not yet certain about how to handle this as well.

**Comment by mickmister** [comment]
Hi @christianhueserhzdr, thanks for creating this issue! I'll need to gather some info to fully understand your use case.

Is each involved repository in the same GitHub org? If this is the case, then you can create one webhook for the whole organization, and no other webhooks/secrets need to be created.

If repositories are in different GitHub organizations, then you will need to create a webhook for each of the repositories or organizations involved. If your use case isn't properly supported, the plugin will need to be able to support multiple secrets if you would like to have the secrets not be shared.

As far as someone having access to the secret: The user would be able to impersonate GitHub webhook calls and act like GitHub events are occurring, which can create subscription and DM notifications inside of Mattermost. Not much of a security risk in that there is no data leakage here, but it of course poses an issue either way.

**Comment by christianhueserhzdr** [comment]
Dear Michael @mickmister,

thank you very much for your response and explaining a bit more how these subscriptions and webhooks work and the security issue regarding webhook secrets.

Our use case is the following:

Some Mattermost users have their own repositories on GitHub not related to any GitHub organization and if they belong to a GitHub organization then they belong to different ones which are not owned by our team. They all would like to make use of the Mattermost Plugin GitHub.

Now, as far as I understood the plugin we can only create webhooks in repositories and GitHub organisations that we own if we do not want to share the webhook secret. That's why we created a webhook in a GitHub organization which we own. The difficulty we now face is that these mentioned users do not want to move their repositories to our GitHub organization, because their work is not related to ours. But if I understood you right there is no way to create a webhook for all of these user repositories to connect them to Mattermost without sharing the webhook secret. Is that correct?

In consequence, you suggested to create a feature request that the plugin needs to be able to support multiple secrets? Did I understand your response right? But is this then less a security issue if these users get a personal webhook secret for their repositories? They would still be able to abuse this secret and to use it to impersonate GitHub webhook calls, right?

Thanks again. I have a better understanding of the functioning of the plugin now.

**Comment by mickmister** [comment]
@christianhueserhzdr I see. This use case is a bit complicated, as there are repositories that you do not control, yet the maintainers of those repositories want to use the plugin on the same Mattermost server that you are running?

It seems the easiest solution is to share the secret. I suppose the security of that decision would depend on how much you trust the admins of these repositories. I think it's important to note that this situation is limited by how GitHub webhooks work, and not so much the Mattermost plugin. Setting up webhooks for repositories you don't control is not a common pattern.

> They would still be able to abuse this secret and to use it to impersonate GitHub webhook calls, right?

Yes, though they would only be able to impersonate the repositories associated with their secret. If all repositories are using the same secret, then any of those repositories can be impersonated by anyone that knows the secret.

A sort of wild idea would be to fork these repositories internally, and use a tool to keep them in sync. This tool actually creates pull requests in the fork to match what is created in the upstream repo https://github.com/backstrokeapp/server. The problem would be that the author of the pull requests would not be reflected in the webhook calls, so you lose that context in the messages posted from the plugin's subscriptions.
