### ISSUE TITLE
Enhancement: Make it possible to configure multiple GitHub Organizations

### ISSUE THREAD

**Issue by steve-todorov** [mattermost/mattermost-plugin-github#552]
Hi,

The existing configuration allows you to lock the plugin to a single organization.
This is fine, but sometimes you might have an OSS community that manages a few projects under different organizations. 
In that situation you would not be able to subscribe to issues from any other organization other than the configured one in the System Console.

I would like to propose to allow the usage of multiple GitHub organizations (i.e. separated by space or comma)
This would allow users to subscribe for notifications only from the mentioned organizations and the repositories inside them.

**Comment by hanzei** [comment]
a comma separated list sounds good to me :+1:

**Comment by khareyash05** [comment]
Hey @hanzei Is this issue open ? I would like to work on the same.

**Comment by hanzei** [comment]
All yours @khareyash05 :+1:
