### ISSUE TITLE
Duplicate bot DM is being created when a user is mentioned on a PR assigned to the user

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#558]
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/6913320/162247501-1965a259-3bdb-4ac4-aa6e-530c850e5c1c.png">

**Comment by hanzei** [comment]
@mickmister Do you know if this is a regression?

**Comment by mickmister** [comment]
@hanzei I do not know. I haven't looked into the issue other than creating this ticket

**Comment by mickmister** [comment]
@Kshitij-Katiyar This was discussed here https://github.com/mattermost/mattermost-plugin-github/pull/559#discussion_r846236152 but there was no conclusion made. Ideally we can say "mentioned in a PR assigned to you", but if not I think just "mentioned you in a comment" works
