### ISSUE TITLE
Connecting without code access

### ISSUE THREAD

**Issue by bivald** [mattermost/mattermost-plugin-github#564]
Hi!

I would like to install this to allow developers to get notifications when they are assigned a PR, but I'm not comfortable giving out code access to Mattermost Github Auth Tokens. Can this plugin work with only scope to read PR:s, not read code? I've been trying to read the code and see what scopes it asks for, but haven't found anything (my Go is very rudimentary) 

Regards,
Niklas

**Comment by catalintomai** [comment]
@bivald - can you detail "to read PR:s, not read code" - why would someone want to have access to the PR but not to the code of the PR? - unless we are missing smth. Is this a private/public repo kind of question?

**Comment by bivald** [comment]
Yes of course! @catalintomai - We're in a highly locked down environment with only private repos. And after the Github Oauth scare with Travis and Heroku token leaking we've basically changed our policy to say that no Github Application besides Google Cloud Builder can have Read Source level (so the tokens can't leak). However we still want as much developer friendly things as possible, including having notifications when PR's are created/updated/assigned so even though the application can't read the actual source code it can still notify us that PR:s are available and such. 

Does that make sense?

**Comment by catalintomai** [comment]
@DHaussermann - is this something we already support - if users connect without the "private" parameter - would that solve this request?

**Comment by catalintomai** [comment]
@mickmister , can you help @bivald with more details on the right flow? Thanks!

**Comment by mickmister** [comment]
>  We're in a highly locked down environment with only private repos
> And after the Github Oauth scare with Travis and Heroku token leaking we've basically changed our policy to say that no Github Application besides Google Cloud Builder can have Read Source level (so the tokens can't leak).

@bivald It looks like we could support this by using the `repo:status` OAuth scope shown here https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes:

> Grants read/write access to commit statuses in public and private repositories. This scope is only necessary to grant other users or services access to private repository commit statuses without granting access to the code.

**Comment by mickmister** [comment]
@bivald Actually I think this may be possible with the current behavior of the plugin. If you set the `Enable Private Repositories` plugin setting to false, and then have the user's connect their account, they will not have permissions to read any code.

Then you can configure a webhook to send you information about the private repo's events. These events don't contain any code in them, unless there is code in the descriptions or comments. I think that is unavoidable in any webhook scenario with GitHub.

![image](https://user-images.githubusercontent.com/6913320/180584743-6a5742e3-5593-4440-9caa-b43f4e3f13e7.png)

**Comment by bivald** [comment]
Awesome! Thank you, I'm closing this then.
