### ISSUE TITLE
Support for all github webhook events

### ISSUE THREAD

**Issue by florius0** [mattermost/mattermost-plugin-github#565]
Hi!

Can you add support for every github webhook [event](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads), or at least for GitHub Actions and Releases events?

**Comment by thoratvinod** [comment]
Hello, I am interested in this issue, May I take this up?

**Comment by hanzei** [comment]
Sure, @thoratvinod :+1:
