### ISSUE TITLE
Conflicting behavior with `UsePreregisteredApplication` and `EnterpriseBaseURL` config settings

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#576]
At the moment, the plugin ignores the `EnterpriseBaseURL` setting if `UsePreregisteredApplication` is set to `true`. The `UsePreregisteredApplication` setting's description is currently:

>  When true, instructs the plugin to use the preregistered GitHub OAuth application - application registration steps can be skipped. Requires [Chimera Proxy](https://github.com/mattermost/chimera) URL to be configured for the server. Cannot be used with GitHub enterprise. **This setting is intended to be used with Mattermost Cloud instances only.**

A customer ran into this issue that is both on Cloud and using GitHub Enterprise. We should make it clearer that this setting cannot be used with GitHub enterprise. Maybe begin the description with "Set to `false` if using GitHub Enterprise".

**Comment by nydhy** [comment]
Hey @hanzei @mickmister !
Is this issue up for grabs? If yes, I'd like to take this up.

**Comment by hanzei** [comment]
Sure, this is up for grabs. Thanks for taking a look @nydhy :+1:
