### ISSUE TITLE
Connecting without write access

### ISSUE THREAD

**Issue by aaronalphonso** [mattermost/mattermost-plugin-github#592]
Hello and thanks for creating this plugin! :)

I'd like to be able to connect my mattermost account with github without granting write access to all my repositories. I want to receive pull request notifications on mattermost for public and private repositories.

I am curious about why the plugin requires write access, and if there is any configuration that would allow the plugin to work with just read access. 

![Imgur](https://i.imgur.com/Ef3GKy2l.jpg)

**Comment by hanzei** [comment]
I don't think that's possible. Per https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes the repo scope always allows read and write access.

**Comment by Kshitij-Katiyar** [comment]
@hanzei @aaronalphonso Can we close this issue?
