### ISSUE TITLE
Add Slash command for creating a new Github Issue

### ISSUE THREAD

**Issue by asatkinson** [mattermost/mattermost-plugin-github#617]
This slash command would have the syntax:
`/github issue create XXX`
where XXX would be an optional string that would be entered into the issue summary field

The issue should appear as it does when the user selects Create Github Issue from the Post actions menu as show below except the description field is blank

<img width="360" alt="image" src="https://user-images.githubusercontent.com/45946404/204654927-00a1bb8d-0e60-46e3-889b-2ca61b910ecc.png">

**Comment by hanzei** [comment]
@asatkinson What is missing from the existing `/github issue create` command that already exists?
![Screenshot from 2022-12-07 21-40-14](https://user-images.githubusercontent.com/16541325/206291108-f69042d3-aa9d-45f1-ab71-2de64c608156.png)

**Comment by Kshitij-Katiyar** [comment]
@ashishbhate @mickmister The GitHub create issue already exists. Right now the only parameter it has is the title which gets prefield in the ``` Title```field of the modal whereas in the issue above the parameter is ``` Summary``` which will get prefield in the description field of the modal. So we can combine both of the parameters.So the slash command will look something like this:-

```/github issue create XXX YYY```
```XXX``` is the title.
```YYY``` is the description.

**Comment by hanzei** [comment]
2/5 that the UX of writing a description directly in the message input box is not great and it's not worth adding support for inputting a description directly in the box.

**Comment by mickmister** [comment]
Closing, as this feature already exists as described in this ticket's description
