### ISSUE TITLE
Can't delete specific subscription from channel

### ISSUE THREAD

**Issue by L3on1d** [mattermost/mattermost-plugin-github#643]
Hi!

After reconfiguring Github plugin, I see two identical subscriptions in channel, first one with two uppercase letters and another one with lowercase. 

For example: MyTeam/repository and myteam/repository

When I'm trying to delete old subscription with uppercase letters it's always deletes lowercase repository. When I trying to delete both, then add only one with lowercase it adds both.

Mattermost Version: 7.7.1
Database Schema Version: 100
Database: mysql

**Comment by hanzei** [comment]
@Brightscout Let's double check how the casein of repos names is handled

**Comment by raghavaggarwal2308** [comment]
@hanzei According to my understanding of the code the name of the repo and owner is first converted to lowercase before the creation of the subscription. So even if the user is using a different casing it will be considered the same. I also tried reproducing this on my local but was unable to do so. Maybe somebody updated the code as now I don't think this issue can occur. Please let us know if we are missing something.

**Comment by mkdbns** [comment]
@hanzei does the above comment satisfy your ask? Should we close this out?

**Comment by hanzei** [comment]
I think we can close this.
