### ISSUE TITLE
Hide UsePreregisteredApplication on on-prem instances

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#647]
The `UsePreregisteredApplication` setting should only be used on Cloud instances. To avoid confusion, the settings should not be visible on on-prem instances. This can be done using the [`hosting`](https://developers.mattermost.com/integrate/plugins/manifest-reference/#settings_schema.settings.hosting) field.

**Comment by Kshitij-Katiyar** [comment]
sure @hanzei working on this.

**Comment by hanzei** [comment]
Thanks @Kshitij-Katiyar :+1:
