### ISSUE TITLE
[Enhancement Proposal] Delaying Draft Pull Request Notifications until Marked as 'Ready for Review'

### ISSUE THREAD

**Issue by weiiwang01** [mattermost/mattermost-plugin-github#680]
Hello, within our organization, we commonly utilize draft pull requests for experimental ideas and prototyping, and convert these drafts pull requests once they are ready for review. 

At present, the GitHub plugin can trigger a notification whenever a new pull request is created, regardless of it's draft or not. However, it does not send out a notification when that draft pull request is marked as 'ready for review'. 

This leads to these pull requests sometimes being overlooked, particularly where there is a long delay between the time of creation and the point at which they are marked ready for review.

As an user, I would appreciate the incorporation of an option that change this behavior so that it could suppress notifications for draft pull requests initially, and instead, issue a notification only when the pull request is converted to 'ready for review'.

**Comment by abdulsmapara** [comment]
Can I take this issue ?

**Comment by hanzei** [comment]
@abdulsmapara Sure :+1:

**Comment by hanzei** [comment]
Thanks for the detailed proposal, @weiiwang01 . A channel message when a PR is ready for review sounds good to me. I'm not too keen on adding another setting. What do you think about the following change?
- When a draft PR is submitted, an on-line notification gets posted.
- When a draft PR is marked as ready-for-review, a "standard" PR notification with the full body gets posted.

**Comment by weiiwang01** [comment]
> Thanks for the detailed proposal, @weiiwang01 . A channel message when a PR is ready for review sounds good to me. I'm not too keen on adding another setting. What do you think about the following change?
> 
> * When a draft PR is submitted, an on-line notification gets posted.
> * When a draft PR is marked as ready-for-review, a "standard" PR notification with the full body gets posted.

Yes, that's perfect, thanks!

**Comment by abdulsmapara** [comment]
@hanzei while setting up the local environment with this plugin, for working on this issue, I am not able to get the notification, getting the following error:

{"timestamp":"2023-06-11 11:53:22.053 +05:30","level":"warn","msg":"Failed to list notifications","caller":"app/plugin_api.go:979","plugin_id":"github","userid":"rpgbs5axo3f498uzxfm7rxpqhc","github username":"abdulsmapara11","error":"GET https://api.github.com/notifications: **403 Resource not accessible by integration** []"}

I am able to see the updates in the panel, which means the plugin is connected to the github.

<img width="257" alt="image" src="https://github.com/mattermost/mattermost-plugin-github/assets/32198670/7259a8d1-38a2-4d76-b2db-0d407c690710">


Can you please help me resolve it ?
