### ISSUE TITLE
Cannot link Github account via the Mattermost Mac desktop app

### ISSUE THREAD

**Issue by stylianosrigas** [mattermost/mattermost-plugin-github#69]
Trying to link github account via the Mattermost Mac desktop app leads to a popup window where the authorize button cannot be clicked. Trying to link the github account via the Mattermost Webapp(Chrome) is successful.

**Comment by tgly307** [comment]
same

**Comment by jasonblais** [comment]
Which version of the desktop app do you have (via Help > Version in the menu bar), and which MacOS version?

I tried on macOS Sierra, Desktop App v4.2.0, and it worked for me.

**Comment by stylianosrigas** [comment]
@jasonblais macOS Mojave (10.14.3) and Mattermost v4.2.1.

**Comment by jasonblais** [comment]
Hm, works on Mattermost Destkop v4.2.1 for me as well..which macOS version do you have @tgly307? Maybe the issue is dependent on the macOS version.

**Comment by tgly307** [comment]
@jasonblais I tried this on windows10, app version 4.2.0. I tried this again and it works, so I guess it maybe a network issue.

**Comment by stylianosrigas** [comment]
@jasonblais I gave it another go and it works for me too. Should I close this issue?

**Comment by jasonblais** [comment]
Thanks for both of you! Let's close for now until we've got reliable repro steps to investigate further

**Comment by BarakStout** [comment]
Had the same issue on Mac. Updating to the latest Mattermost client app resolved the issue. FYI.
