### ISSUE TITLE
unusable links in plugin messages

### ISSUE THREAD

**Issue by ChristophHoyer** [mattermost/mattermost-plugin-github#693]
Hej there!

Whenever I get a notification from the Mattermost-GitHub plugin it includes links to nowhere.
![image](https://github.com/mattermost/mattermost-plugin-github/assets/48314145/2f1f3fd0-13e5-474e-910a-558ffc9c70f0)

The slash in front of the message just leads to https://<mygithub>.com//
![image](https://github.com/mattermost/mattermost-plugin-github/assets/48314145/92546acf-a565-4ed6-9441-fe0ad3368453)

And when I click on the message, it gets a warning about a missing app for "about" links in the desktop app and only opens a "about:blank#blocked" page in the browser.
![image](https://github.com/mattermost/mattermost-plugin-github/assets/48314145/589354c2-9fcc-4d53-88fb-f581c2ee1e3d)

**Comment by Kshitij-Katiyar** [comment]
@ChristophHoyer  I am unable to reproduce the above issue. Please share your build version, mattermost server version, and any other detail relevant to this issue.

**Comment by ChristophHoyer** [comment]
sure, here you go:

```
Mattermost Enterprise Edition
Modern communication from behind your firewall.

Mattermost Version: 7.8.9
Database Schema Version: 107
Database: mysql
Licensed to: XXXXXXXXXXXXXXXXXX
Learn more about Enterprise Edition at [mattermost.com](https://mattermost.com/)
Copyright 2015 - 2023 Mattermost, Inc. All rights reserved
[Terms of Use](https://mattermost.com/terms-of-use/) - [Privacy Policy](https://mattermost.com/privacy-policy/)
Mattermost is made possible by the open source software used in our [server](https://github.com/mattermost/mattermost-server/blob/master/NOTICE.txt), [desktop](https://github.com/mattermost/desktop/blob/master/NOTICE.txt) and [mobile](https://github.com/mattermost/mattermost-mobile/blob/master/NOTICE.txt) apps.

Build Hash: 6c6da2672849c1f0ca41efec67bea8391615cd69
EE Build Hash: 2238ac8bcac3dc0a95ca5330c5c3288282b13c38
Webapp Build Hash: 65aaab5fbf802cd64b8093c1b180ee23593e0cc3
Build Date: Mon Jul 24 10:29:41 UTC 2023
```

By the way: the first link should lead to an action run, the second one to a discussion.
Links to issues or pull requests are working on my side as well.
