### ISSUE TITLE
Push events: option to show commit author instead of committer

### ISSUE THREAD

**Issue by cpatulea** [mattermost/mattermost-plugin-github#719]
Hi, we have enabled Github integration in our Mattermost instance and enjoy it.

For example we received this push event:

<img width="644" alt="image" src="https://github.com/mattermost/mattermost-plugin-github/assets/167134/74c0139d-9980-4665-aaf9-e6360ee44880">

but, the commit was not authored by me, it was authored by someone else: https://github.com/FOULAB/foulab-dot-org-hugo/commit/f35cb831b694fd17f23ac4f6c3bc8798ca2ad2c0

We would like the original author in the notifications. Would it be possible to have an option for that?

I believe the template is here: https://github.com/mattermost/mattermost-plugin-github/blob/d8fb0014f6012dc35814bbd6f5252bc8fa855b64/server/plugin/template.go#L273

**Comment by cpatulea** [comment]
Here's a high level draft: https://github.com/mattermost/mattermost-plugin-github/commit/b3024faf70009e85d887081555d4439def48fae2

Does this seems like a good approach? If so, I'll go through the contribution guidelines in more detail and submit a formal PR.

**Comment by hanzei** [comment]
@raghavaggarwal2308 Can you please provide guidance here for the next steps?

**Comment by raghavaggarwal2308** [comment]
@hanzei @cpatulea The approach looks fine to me. We can properly review the commit once the PR is submitted.

As a next step, you can submit a PR against the `master` branch. You can take reference from this https://github.com/mattermost/mattermost-plugin-github/pull/718 PR and add the necessary info in the description.

**Comment by cpatulea** [comment]
Thanks for the merge!

What's the general release process for mattermost-plugin-github? We're currently running stable v2.1.7 - would this feature be backported to the 2.1 branch? I also see a v2.2.0-rc3, what's a typical timeline for those to become stable?

**Comment by cpatulea** [comment]
For my own reference, looks like this was released in v2.2.0 on Feb 13: https://github.com/mattermost/mattermost-plugin-github/releases/tag/v2.2.0
