### ISSUE TITLE
Use proper bot account

### ISSUE THREAD

**Issue by clarfon** [mattermost/mattermost-plugin-github#72]
Mattermost 5.10 now allows bot accounts, and having a proper bot account instead of having to make a separate account for the bot would be nice.

**Comment by jwilander** [comment]
@crspeller you had a branch for that right?

**Comment by crspeller** [comment]
Yup. I will submit that when I get a chance.

**Comment by crspeller** [comment]
Closed by https://github.com/mattermost/mattermost-plugin-github/pull/83
