### ISSUE TITLE
Feature Request: Subscribe to GitHub Action workflow failures

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#722]
Some information we can include in the resulting post:

- Name of workflow
- Link to failed workflow run, and/or step that failed
- Link to any associated PR, or branch this was run on
- Possibly show a log of the run output associated with the failure, but this could be noisy and unhelpful if the logs at the end of the step failure are not related to the actual issue happening

**Comment by miro-trifonov** [comment]
I'm aware of this tool https://github.com/marketplace/actions/notify-slack-action existing for slack. If it can be configured to also work with mattermost, that could be a good solution to this feature request.

**Comment by mickmister** [comment]
@miro-trifonov It looks like it sends a property `text` in its payload, so it may be compatible with Mattermost's slack-compatible webhooks https://developers.mattermost.com/integrate/webhooks/incoming. @miro-trifonov Are you willing to try this out?

**Comment by miro-trifonov** [comment]
Yes, we have this in the backlog, I will reach out when we start working on the functionality.
