### ISSUE TITLE
The message generated for the `/github subscriptions list ` slash command should show the excluded repositories (if present).

### ISSUE THREAD

**Issue by arush-vashishtha** [mattermost/mattermost-plugin-github#728]
### Summary
The feature implemented in the PR https://github.com/mattermost/mattermost-plugin-github/pull/683 should also contain the feature to show the list of excluded repositories in the list of subscriptions.
### Steps to reproduce

1. Enter the slash command `/github subscriptions add <organization> --exclude <repo> <feature> ` in the desired channel and create subscription for the organization with some repositories excluded.
2. Navigate to the desired channel or DM/GM on MM and enter the slash command `/github subscriptions list `.

### Expected behavior
The created subscription should show the details of the excluded repositories along with the events in the list of subscriptions.
### Actual behavior
Showing only the subscriptions in the desired channel or DM/GM on MM.
### ScreenShots
![image](https://github.com/mattermost/mattermost-plugin-github/assets/145128655/794700ea-94a8-49fb-8e37-c4e1e03e4a83)

**Comment by hanzei** [comment]
Good catch @arush-vashishtha :+1:

**Comment by raghavaggarwal2308** [comment]
@hanzei @mickmister This issue is not reproducible anymore. I have verified the same with @arush-vashishtha as well. Maybe it was a glitch earlier.
![image](https://github.com/mattermost/mattermost-plugin-github/assets/55234496/51fad9ae-2ea0-43be-813d-35dacd35426b)
