### ISSUE TITLE
Github enterprise support

### ISSUE THREAD

**Issue by pranereddy** [mattermost/mattermost-plugin-github#76]
Is on-prem Github enterprise supported, is it possible to subscribe to github events based on mattermost channels, userids like userA wants to send all github events from OrgA to channel A.

**Comment by jasonblais** [comment]
Hey @pranereddy - GitHub Enterprise and channel subscriptions are supported. See a list of features available here: https://github.com/mattermost/mattermost-plugin-github#features

**Comment by pranereddy** [comment]
Hey @jasonblais Thanks for the quick response, would you please share some more info on how to subscribe channels for particular org/repo using /github.

**Comment by jasonblais** [comment]
hey @pranereddy, you can use `/github subscribe` to subscribe a Mattermost channel to receive posts for new pull requests and/or issues in a GitHub repository.

If you run `/github help` in Mattermost, it will provide you more detailed information of that command

![image](https://user-images.githubusercontent.com/13119842/58479880-21a9e200-8127-11e9-870c-b0fc00eee907.png)

**Comment by jasonblais** [comment]
I've also created an issue to document all slash commands in the README file https://github.com/mattermost/mattermost-plugin-github/issues/77

**Comment by pranereddy** [comment]
@jasonblais cool, thanks a lot 🙂

**Comment by jasonblais** [comment]
Certainly! If you have any feedback on the plugin, would love to hear :)

**Comment by pranereddy** [comment]
Sure, will do.
