### ISSUE TITLE
How to remove GitHub integration in mattermost?

### ISSUE THREAD

**Issue by patricorgi** [mattermost/mattermost-plugin-github#781]
I accidentally added github integration and it shows up on my sidebar, and later realized I don't use GitHub with the rest of my team on mattermost. Therefore, I would like to remove it. However, it's rather obscure to me where I can manage all the integrations. 

<img width="115" alt="Screenshot2024-05-13 下午2 46 51" src="https://github.com/mattermost/mattermost-plugin-github/assets/15998986/73ebacfc-6837-44b0-b5f1-e7a092b0ee75">

It does not show up in my "Incoming Webhooks".

<img width="1482" alt="Screenshot2024-05-13 下午2 48 32" src="https://github.com/mattermost/mattermost-plugin-github/assets/15998986/4a5c37df-4b7e-4a47-96aa-685767812e9b">

Could you please instruct me how to remove it?

**Comment by ThiefMaster** [comment]
It's a plugin, not an integration. You can disable/uninstall it in the System Admin Console

**Comment by patricorgi** [comment]
How to access System Admin Console? Googled results say I can find it at the top-left corner of the app. However, I could not spot such an access there.
<img width="448" alt="Screenshot2024-05-13 下午3 15 37" src="https://github.com/mattermost/mattermost-plugin-github/assets/15998986/2c8afb2a-a37c-4846-89b6-ff1953044361">

**Comment by mickmister** [comment]
Hi @patricorgi, thanks for filing this issue. What is your expected outcome here? Do you want the integration disabled for everyone on your server?

**Comment by patricorgi** [comment]
Hi @mickmister thanks for replying. I hope to uninstall the GitHub plugin. I don't think this plugin is installed for everyone on the server. This is a collaboration server, and I don't have the control of it. If memory serves, I added the GitHub plugin by myself, and now I don't know how to get rid of it.

**Comment by mickmister** [comment]
@patricorgi The plugin is installed server-wide, and cannot be disabled per-user or per-team. A system admin must have installed this on your server.

There is a global plugin setting `Display Notification Counters in Left Sidebar` that can remove the PR counts on the left side of the screen for all users, in case this is the desired functionality. Does this help @patricorgi?

**Comment by patricorgi** [comment]
I cannot find the option `Display Notification Counters in Left Sidebar`. Could you illustrate it with screenshots? I realized that my Mattermost app must have a very different interface.

**Comment by mickmister** [comment]
@patricorgi You need to be a system admin to see those plugin settings. They are present at `https://(MM_SITE_URL)/admin_console/plugins/plugin_github`

![image](https://github.com/mattermost/mattermost-plugin-github/assets/6913320/de475423-ce57-4983-b045-bdf774dfecc9)

**Comment by patricorgi** [comment]
I see. Many thanks for your patience and explanations.
