### ISSUE TITLE
Provide a more clear error message when the wrong content type is selected for a webhook

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-github#95]
Repro:

1. Follow these steps to configure the GitHub plugin: https://github.com/mattermost/mattermost-plugin-github/#configuration
  - NOTE: To reproduce the error in this issue, when creating the webhook in GitHub in step 2, **do not** change the content type to "application/json"
3. Connect your Mattermost account to GitHub with `/github connect`.
4. Subscribe a channel to receive notifications with `/github subscribe owner/repo`.
5. Trigger an event such as opening an issue in the GitHub repository you subscribed.

Observed: No event, with the following error in server logs

```
2019-06-17T13:35:18.794Z    info    go-plugin/stream.go:15    {"level":"error","msg":"invalid character 'p' looking for beginning of value"}    {"plugin_id": "github", "source": "plugin_stdout"}
```

Proposed change: 
1. Update the server log error message to state `GitHub webhook content type should be set to "application/json"`
2. Fail the request with a proper status code so that the webhook shows up as failed on GitHub

**Comment by niklabh** [comment]
Here is a pull request: https://github.com/mattermost/mattermost-plugin-github/pull/121
